### ISSUE TITLE
grafana-server segfaults because the stack used by Cgo is too small

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#217] opened 2024-01-22 22:01 UTC
### What happened?

grafana-server frequently segfaults and gets restarted by systemd, but without anything useful in the grafana logs (even with the log level raised to debug). After some (insane) investigation by a co-worker they determined that the segfault always occurrs while calling into sqlite code. The segfault occurs because the C call stack is too deep and goes past the memory allocated for the stack.

Despite the system rlimit for stacks being 8MB, grafana-server thinks that the C stack size is 128K because it's built against musl. musl doesn't query the system for the stack size as per https://wiki.musl-libc.org/functional-differences-from-glibc.html#Thread-stack-size. 128K is too small for what grafana is doing.

My co-worker tried to use https://github.com/yaegashi/muslstack to patch the stack size, but the musl that grafana-server is built against appears to be too old and doesn't use the value from the PT_GNU_STACK header. Instead they used the following to patch the binary:

```

gdb --write /usr/share/grafana/bin/grafana -batch -ex "set __default_stacksize = 8388608"

```

grafana-server now runs reliably. We haven't experienced a segfault in the last 12 hours, where previously it would often crash after a couple of http requests from certain users in our org.

### What did you expect to happen?

grafana-server shouldn't segfault.

### Did this work before?

Probably not, but this is our first time with this combination of packages and operating system so we don't know.

Previously we were using our own builds of Grafana on Illumos and OpenBSD, which don't use musl.

### How do we reproduce it?

Hard to say.

Our grafana is set up behind nginx with `auth.proxy` for authentication. Everything else is largely defaults otherwise. The problem mostly occurs with Viewers looking at a dashboard backed by a Clickhouse datasource.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.2 and 10.2.3

OS: Ubuntu 22.04.1 LTS on an LX branded zone on Triton Datacenter (https://www.tritondatacenter.com/)

Browser: Firefox and Chrome, but I don't think it matters

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment] 2024-01-22 22:01
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79773

**Comment by moxious** [comment] 2024-01-22 22:02
**Summary**: The GitHub issue reports that 'grafana-server' frequently crashes due to segmentation faults when calling into SQLite code as a result of a stack size that is too small (128K) for its operations, which stems from being built against musl that does not query the system for stack size. A temporary fix through GDB to set the stack size to 8MB has led to stable operation without segfaults. The issue is open and occurred on the Ubuntu system running Grafana versions 10.2.2 and 10.2.3.

**Comment by moxious** [comment] 2024-01-22 22:02
Hi @tonypowa, 

It sounds like you've run into a significant issue that touches on the back-end infrastructure of Grafana. Since the problem involves the grafana-server binary and backend interaction with musl, I believe this issue is best directed towards the **Backend Platform project**. 

The development team responsible for that area should be able to investigate the stack size limitation, how musl is being used, and how that affects the stability on different systems like the one you've described. I suggest opening an issue in the Backend Platform project repository and linking to the details you provided here.

Thank you for your detailed report and for the initiative your co-worker took in identifying this issue!

**Comment by moxious** [comment] 2024-01-22 22:02
**Elaboration**:


Thank you for the detailed issue report about `grafana-server` experiencing segfaults due to an insufficient C call stack size when using `musl`. To help us better understand and address the issue, could you please provide additional information on the following points?

1. Could you share the output of the segfault error from the system logs (e.g., `/var/log/syslog`, `dmesg`, or `journalctl` for systemd)? This might contain valuable information regarding the stack trace at the time of the crash.

2. Please provide the specific versions of `musl` and `sqlite` that are being used by `grafana-server` on your system.

3. Could you confirm whether the issue occurs consistently when performing a particular action or accessing a specific dashboard? If so, could you provide steps to reliably reproduce the segfault or even share the dashboard configuration (with any sensitive information removed)?

4. Have you tried building `grafana-server` against a different libc (e.g., glibc) to see if the issue persists?

5. Any additional changes made to the default Grafana configuration or related system configurations that might be relevant would be useful.

Please feel free to reach out if you have any questions or need assistance providing the requested information. Your collaboration is crucial in resolving this issue. Thank you!

**Comment by tonypowa** [comment] 2024-01-22 22:10
really complex issue for me so i am glad i have you !

**Closed** 2024-09-27 10:43 UTC
