### ISSUE TITLE
Dashboards: Template variables got refreshed when come back to dashboard from a panel by pressing ESC key

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#278] opened 2024-02-21 12:57 UTC
### What happened?

My Grafana version is 9.5.14. Template variables got refreshed when come back to dashboard from a panel by pressing ESC key. Time range doesn't change, but variables refreshed.

### What did you expect to happen?

Variable doesn't refresh

### Did this work before?

In Grafana 8.5, it works fine.

### How do we reproduce it?

1. Create a dashboard with some template variables on time range change.

2. View/Edit a panel.

3. Press ESC to return to the dashboard.

4. Some times the variables get refreshed.

### Environment (with versions)?

Grafana: 9.5.14

OS:

Browser:

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment] 2024-02-21 12:57
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81248

**Comment by moxious** [comment] 2024-02-21 12:58
**Summary**: In Grafana v9.5.14, template variables unexpectedly refresh when returning to the dashboard from a panel by pressing the ESC key, an issue which did not occur in Grafana v8.5.

**Comment by moxious** [comment] 2024-02-21 12:58
Hello @tonypowa, this seems related to the dashboard template variables, which might fall under the **Frontend Platform project** as it deals with how the UI behaves and manages state transitions. I'd recommend transferring this issue to the Frontend Platform project so the respective team can look into the unexpected refresh behavior of template variables when navigating in the UI.

```
/transfer Frontend Platform project
```

**Comment by moxious** [comment] 2024-02-21 12:58
**Elaboration**:


Hi @tonypowa, thank you for reporting the issue you've encountered with Grafana's template variables refreshing unexpectedly. To help us further investigate and resolve this problem, could you please provide us with some additional information? Here are a few clarifying questions and requests for more details that would be extremely helpful:

- Is there any specific pattern or consistency regarding when the variables refresh upon ESC return? For instance, does it always happen, or only under certain conditions?
- Could you provide screenshots or a short video demonstrating the issue? It would be particularly helpful to see the before and after states of the template variables.
- Is there any error message or console log in the browser's developer tools that appears when the issue occurs? If so, please include them.
- Can you specify which OS and Browser you are using, and version numbers if possible?
- Does the issue happen with all browsers and operating systems, or have you noticed it only on specific ones?
- Have you made any custom modifications or are using any plugins that might be influencing the behavior of the dashboard?
- Could you share the JSON model of the dashboard where the issue occurs (if there's no sensitive data)? If sensitive data is contained within the dashboard, could you create and share a minimally reproducible example where the issue still occurs?

The more details you can provide, the better we will be able to understand the cause of the problem and find a resolution. Looking forward to your response!

**Closed** 2024-09-27 10:41 UTC
