### ISSUE TITLE
Unable to build Grafana backend on Ubuntu

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#159] opened 2023-12-14 11:41 UTC
### What happened?

Getting the following error on `make run`:

```

:

:

build go files

go run build.go -dev build

Version: 10.3.0, Linux Version: 10.3.0, Package Iteration: 1700832720pre

building binaries build

building grafana ./pkg/cmd/grafana

go build -ldflags -w -X main.version=10.3.0-pre -X main.commit=7a46d6a1b3 -X main.buildstamp=1700828574 -X main.buildBranch=main -o ./bin/grafana ./pkg/cmd/grafana

# github.com/grafana/grafana/pkg/services/sqlstore/migrator

pkg/services/sqlstore/migrator/sqlite_dialect.go:131:24: undefined: sqlite3.Error

pkg/services/sqlstore/migrator/sqlite_dialect.go:142:24: undefined: sqlite3.Error

pkg/services/sqlstore/migrator/sqlite_dialect.go:150:41: undefined: sqlite3.ErrConstraintUnique

pkg/services/sqlstore/migrator/sqlite_dialect.go:150:98: undefined: sqlite3.ErrConstraintPrimaryKey

exit status 1

exit status 1

make[1]: ISSUE_TRIAGE.md README.md copy-issue.sh grafana-labels.txt grafana-triage-labels.txt [Makefile:125: build-go] Error 1

:

:

```

Firstly, I tried running Grafana on Windows but couldn't get `make run` to pass and then tried on WSL2, in the hope that this approach might work.

### What did you expect to happen?

Make should start the backend server as specified in documentation.

### Did this work before?

NA

### How do we reproduce it?

1. Clone repo.

2. Execute `make run`

### Is the bug inside a dashboard panel?

NA

### Environment (with versions)?

Grafana: 10.2.2

OS: WSL2

Browser: NA

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

NA

**Comment by tonypowa** [comment] 2023-12-14 11:41
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78643

**Comment by moxious** [comment] 2023-12-14 11:42
**Triage summary**: The user is experiencing an error when attempting to build the Grafana backend on Ubuntu via WSL2. The issue is related to undefined references in the 'sqlite_dialect.go' file during the build process. Further investigation is needed to identify the root cause of these undefined references.

**Recommended labels**:

area/backend
area/backend/build
type/build-packaging
needs investigation

**Comment by moxious** [comment] 2023-12-14 11:42
Hi @tonypowa, it looks like you might be encountering an issue with the Grafana backend build process. This issue appears to relate to the Backend platform project, and I would recommend transferring this issue to that specific project for a better chance of resolution. The error you've posted suggests there might be a missing dependency or an issue with SQLite libraries. Before transferring, please ensure all prerequisites for building Grafana on Ubuntu via WSL2 are met, as detailed in the Grafana documentation.

**Meta**:

**Comment by moxious** [comment] 2023-12-14 11:42
**Elaboration**: 
  
Hello @tonypowa, thank you for reaching out with the issue you encountered while building Grafana backend on Ubuntu. To help us troubleshoot the error you're experiencing, we need to gather a bit more information about the environment and the exact steps you took. Here are some questions and suggestions that would help us understand the issue better:

1. Can you confirm if you have all the necessary prerequisites installed as per the Grafana documentation? This typically includes Go, Node.js, Yarn, and other build tools required for Grafana.

2. Could you specify the version of Go you’re using? You can provide this by running go version go1.20.12 linux/amd64.

3. Have you made any changes to the codebase or are you building the Grafana project as-is from the repository? If there are changes, could you detail them?

4. Can you provide the full output of the  command, including any output before the error messages? This may give us context on what was happening immediately before the problem occurred.

5. Have you tried cleaning your build environment using  or an equivalent command before running  again?

6. It looks like the issue could be related to missing SQLite dependencies. Did you install all the necessary SQLite dev packages for your system?

7. Finally, could you confirm that you are running the  command within the WSL2 environment and not on native Windows?

Once you provide this additional information, we’ll be better equipped to assist you further. Looking forward to your response!

**Comment by moxious** [comment] 2023-12-14 11:43
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa! :wave:

Looks like there is an issue with the SQLite dependency. The errors in  suggest that the  type and other constants are not recognized, which typically means the SQLite library isn't properly included or can't be found.

Here are some steps you might try to resolve the issue:
1. Ensure that you have the SQLite development libraries installed on your system ( on Ubuntu).
2. Make sure your Go environment is set up correctly and you have the correct version of Go installed.
3. Run  to ensure the SQLite driver for Go is installed.
4. Clean your Go cache with  and try building again.

Also, it might help to check if the issue persists with the latest main branch from the repository. If you continue facing this issue after trying the above steps, we can take a closer look to help you get Grafana up and running!

And here’s a little something to lighten the mood while debugging:

**Why don't scientists trust atoms?**
Because they make up everything!

Keep me posted on your progress!

**Meta**:

**Closed** 2024-09-27 10:43 UTC
Labels: area/backend
