### ISSUE TITLE
[OSS] some Hyperlinks not correct/working with root_url behind HAproxy (path)

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#328] opened 2024-04-11 14:56 UTC
### What happened?

Version: 10.4.0 (OSS)

Having grafana behind HAPROXY, setup like mantioned here: [Configure HAProxy](https://grafana.com/tutorials/run-grafana-behind-a-proxy/) chapter: Configure HAProxy

Also acording i set the grafana.ini with the `root_url` that contain a sub path

```ini

root_url = http://fqn.local/grafana

```

Some hyperlink that are not correct mapped with the path.

### What did you expect to happen?

hyperlinks should work acording the root_url

### Did this work before?

dont know

### How do we reproduce it?

- Home -> Alerting -> Alert rules -> Edit rule -> Preview routing -> See Details -> `See details`

 ERROR --> http://fqn.local/alerting/notifications/receivers/2/edit?alertmanager=grafana

 should be: --> http://fqn.local/grafana/alerting/notifications/receivers/2/edit?alertmanager=grafana

- Home -> Alerting -> Contact points -> `[name cp] is used by 1 notification policy`

 ERROR --> http://fqn.local/grafana/grafana/alerting/routes?contactPoint=1

 should be: --> http://fqn.local/grafana/alerting/routes?contactPoint=1

 --> what is showing: Page not found (404)

 

 --> Click on `home`

 ERROR --> http://fqn.local/

 should be: --> http://fqn.local/grafana

 

- Home -> Alerting -> Notification policies -> Delivered to `[name cp]`

 ERROR --> http://fqn.local/grafana/grafana/alerting/notifications/receivers/2/edit?alertmanager=grafana

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

Docker

**Comment by tonypowa** [comment] 2024-04-11 14:56
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#84468

**Comment by moxious** [comment] 2024-04-11 14:57
Hi @tonypowa, it seems like the issue you're facing is related to incorrect URL mappings when Grafana is behind a reverse proxy. The best team to handle this issue would be the **Backend Platform project** team, as the `root_url` configuration and routing behavior should be managed there. If you haven't already, please make sure to provide them with details of your Grafana version, OS, browser, and any relevant Grafana configuration settings you've adjusted.

**Comment by moxious** [comment] 2024-04-11 14:57
**Summary**: Issue #328 reports incorrect hyperlinks when Grafana (v10.4.0 OSS) is set up behind an HAProxy with a sub-path `root_url`. The user experiences 404 errors due to hyperlinks not incorporating the sub-path as expected. Steps to reproduce involve accessing various alerting and notification links from the Grafana home page.

**Comment by moxious** [comment] 2024-04-11 14:58
**Elaboration**:


Thank you for submitting this issue and providing detailed steps to reproduce the hyperlinks problem with Grafana behind an HAProxy. In order to help you better, we need a bit more information about your setup:

- Could you please share the **exact contents** of the HAProxy configuration related to Grafana, as you mentioned following a tutorial? Specifically, we're looking for any `http-request set-path` or `http-request add-header` directives related to `X-WEBAUTH-USER` and `X-Forwarded-For`.

- Is `root_url` the only parameter you've set in `grafana.ini`, or are there other custom configurations related to base path or proxy settings that you've applied?

- Can you confirm if you are seeing any errors in the Grafana server logs when trying to access these hyperlinks? If so, please copy and paste the logged error messages here.

- In which environment is Docker running (e.g., local machine, cloud provider, Kubernetes)?

- What version of HAProxy are you using? There may be version-specific nuances in the configuration.

- Since you are not sure if it worked before, have you been able to try this same setup with a different version of Grafana to see if the issue persists?

- Lastly, for better context, could you provide a few details on your browser and OS that you are using to access Grafana?

_Once we have this information, we will have a clearer picture of the problem and be able to work towards resolving the issue._

**Closed** 2024-09-27 10:41 UTC
