### ISSUE TITLE
Alerting: transient "Failed to load rules config from Loki: Ruler API is not available for Loki" error

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#261] opened 2024-02-15 09:28 UTC
### What happened?

When I open an existing Grafana-managed alert rule or try to create a new one in the UI, and then close either of them without saving (by clicking "Alert rules"), I get "Failed to load rules config from Loki: Ruler API is not available for Loki" error. As soon as I refresh the page, the error is gone.

Ruler API is enabled and Ruler evaluates the alerting rules that are stored locally. Those alerting rules are also visible by Grafana.

### What did you expect to happen?

No error all the time.

### Did this work before?

It didn't work before, but the error is also appearing only about 70% of the time when I follow the steps below.

### How do we reproduce it?

1. Go to Alerting -> Alert rules

2. Click "New alert rule"

3. Change data source to Loki

4. Click "Alert rules" (either above or at the sidebar)

<img width="667" alt="Screenshot 2024-01-19 at 15 23 37" src="https://github.com/grafana/grafana/assets/101715458/3f388d0b-c292-4f14-850a-4ab1e2ef9bf2">

5. The error appears

<img width="832" alt="Screenshot 2024-01-19 at 15 24 31" src="https://github.com/grafana/grafana/assets/101715458/11fab05f-8264-4b62-9ba6-381773653901">

6. Refresh the page

7. The error is gone

<img width="826" alt="Screenshot 2024-01-19 at 15 24 43" src="https://github.com/grafana/grafana/assets/101715458/04c4d95a-f37c-4cd6-962a-b061fd8918f9">

### Environment (with versions)?

Grafana: 10.1.6

OS: macOS Sonoma 14.2.1

Browser: Chrome 120.0.6099.234

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by tonypowa** [comment] 2024-02-15 09:28
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80895

**Comment by moxious** [comment] 2024-02-15 09:29
Hi @tonypowa! It seems like this issue is related to the **Alerting project** as it deals with Grafana-managed alert rules and the interaction with Loki, including an error regarding the Ruler API. I recommend transferring this issue to the Alerting project so that the right team can take a look at it. They will be able to provide assistance with the intermittent issue you're experiencing with the alert rules configuration.

**Comment by moxious** [comment] 2024-02-15 09:29
**Summary**: The issue involves a transient error in Grafana alerting which says 'Failed to load rules config from Loki: Ruler API is not available for Loki' when managing alert rules. The error appears sporadically (about 70% occurrence) upon closing the alert rule UI without saving and disappears after a page refresh.

**Comment by moxious** [comment] 2024-02-15 09:29
**Elaboration**:


Thank you for the detailed information on the issue you’re experiencing in Grafana with Loki Ruler API. To help us investigate this further, could you please provide us with the following additional information and clarifications? 

1. **Configuration Details**: Can you share the relevant configuration details for Ruler in Loki? This could include any yaml or json configuration file snippets (with sensitive information redacted).

2. **Logs**: Are there any logs from Grafana and Loki, especially at the time when the error appears, that might indicate what's going wrong? If there are any relevant log messages, could you attach them here?

3. **Consistency of Reproduction**: You mentioned the error appears about 70% of the time. Is there anything specific that you have observed that affects whether or not the error occurs, like network issues or specific sequences of actions within the UI?

4. **Troubleshooting Steps**: Have you tried troubleshooting steps such as checking network connectivity between Grafana and Loki, or ensuring there are no proxy issues that might be interfering with the API requests?

5. **Grafana and Loki versions**: Since these types of issues might be version-dependent, are you using the latest versions of Grafana and Loki? If not, could updating to the latest versions be an option for you?

Once we have this additional information, we will be better equipped to understand the cause of the issue and work towards a resolution. Thank you again for contributing to the community by reporting this issue!

**Closed** 2024-09-27 10:42 UTC
