### ISSUE TITLE
Explore: Inconsistency in log colour and "level" label value

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#369] opened 2024-07-04 07:33 UTC
### What happened?

![Screenshot from 2024-06-06 22-10-47](https://github.com/grafana/grafana/assets/1549276/ef060279-bdd4-49ed-880f-15a966a2ce96)

`level` label doesn't correspond to the severity of the log and therefore the colouring is wrong.

### What did you expect to happen?

Critical and debug logs should not be green. Their `level` should not be `info`.

### Did this work before?

No.

### How do we reproduce it?

```python

import json

import logging



import logging_loki





class CustomLokiFormatter(logging.Formatter):

 def format(self, record):

 return json.dumps({

 "level": record.levelname.lower(),

 "message": record.getMessage(),

 })



handler = logging_loki.LokiHandler(

 url="http://localhost:3100/loki/api/v1/push",

 tags={'application': 'test-log-color'},

 version="1",

)

handler.setFormatter(CustomLokiFormatter())



logger = logging.getLogger('test-logger')

logger.setLevel(logging.DEBUG)

logger.addHandler(handler)



logger.debug('Debug log')

logger.info('Info log')

logger.warning('Warning')

logger.error('Error log')

logger.exception('Exception log', exc_info=Exception('Test exception'))

logger.critical('Critical log')



```

### Environment (with versions)?

Grafana: 11.0.0-preview

OS: Ubuntu 20.04

Browser: Brave

### Grafana platform?

Docker

### Datasource(s)?

Loki (main-e9b6ce9)

**Comment by tonypowa** [comment] 2024-07-04 07:33
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88874

**Comment by moxious** [comment] 2024-07-04 07:35
**Elaboration**:


Hello @tonypowa, thank you for taking the time to report the issue. I have a few clarifying questions that would help us better understand and replicate the issue you're facing with log level labeling and color inconsistency in Grafana logs.

1. Could you please confirm if you are using any custom configuration for log level coloring within Grafana apart from the default settings?

2. Can you provide more details on the specific panel or visualization type where you encountered this issue? A screenshot with the problematic log highlighted can be especially helpful.

3. For the `level` label mismatch, could you please let us know if this issue occurs only when you are using the `CustomLokiFormatter`, or is it present even when using the default formatter?

4. Have you observed this behavior consistently across different log entries or does it appear to be erratic? 

5. It would be great if you could share the output observed in the Grafana UI, which shows the `level` discrepancy.

6. Are there any error messages in the Grafana server logs that you could share?

Understanding the context and environment where the issue occurs will allow us to pinpoint the problem more accurately. Once we have the additional information, we can proceed with investigating the issue further.

Looking forward to your response!

**Comment by moxious** [comment] 2024-07-04 07:35
Hello @tonypowa, this seems like an issue affecting log level recognition and colouring which likely pertains to the **Explore** project given it relates to inconsistencies in Grafana's Explore UI for logs visualization. Transferring this issue to the correct team would be important for having the appropriate context and expertise to address this behavior with log data from Loki. In the meantime, as a workaround, you may want to check if there is a custom override or configuration that might be influencing the log level display.

**Comment by moxious** [comment] 2024-07-04 07:35
**Summary**: The issue, opened by tonypowa, reports an inconsistency where the `level` label in Grafana logs does not match the log severity, resulting in incorrect coloring; for example, critical and debug logs are incorrectly colored green and marked as `info`. Reproduction steps with Python code are provided, and the issue is confirmed to occur in a Docker setup using Grafana 11.0.0-preview on Ubuntu with the Loki datasource.

**Closed** 2024-09-27 10:41 UTC
