### ISSUE TITLE
Y axis Soft Min leaves too little margin

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#281] opened 2024-02-26 09:14 UTC
### What happened?

I set a Soft Min on the Y-axis of a slow-changing "disk space free" graph. This works, but leaves too little margin on top of the graph. The line in the graph gets almost clipped away.

### What did you expect to happen?

I expect that Grafana chooses the ranges of the axes, in this case specifically the Y-axis, such that the graph is drawn clearly within the bounds of the axes and not almost clipped off.

### Did this work before?

Don't know, probably not.

### How do we reproduce it?

1. Draw a constant (or slow-changing) graph of rather large value, let's say 1e*12.

2. Set a Soft Min on the Y-axis.

3. The graph does not look nice, there should be more margin on the top such that the line of the graph is drawn clearly within the Y-axis range.

### Environment (with versions)?

Grafana: 9.3.2

OS: Linux

Browser: Latest Firefox

### Grafana platform?

None

**Comment by tonypowa** [comment] 2024-02-26 09:14
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81537

**Comment by moxious** [comment] 2024-02-26 09:15
**Elaboration**:


Hi @tonypowa, thank you for reaching out with this issue. To better understand the problem and find a solution, we’d appreciate a bit more information about the configuration and behavior you’re experiencing. Could you please provide the following details? 

- Screenshots of the graph where the issue is visible, showing the Y-axis with the Soft Min set and the clipped line.
- The JSON model of the Grafana panel where you have set the Soft Min. This will help to reproduce the issue precisely.
- Clarification on the 'Soft Min' value you've set for the Y-axis; if possible, provide the exact number or range.
- Have you tried adjusting any other settings (such as 'Soft Max', 'Min', or 'Max') to achieve the desired appearance?
- Information regarding any custom options or overrides that you may have applied to the panel which could affect axis scaling.

With this additional context, we can further investigate the issue and provide assistance in resolving it. Thank you for your contribution to improving the project!

**Comment by moxious** [comment] 2024-02-26 09:15
Hi @tonypowa, thank you for bringing this to our attention.

It sounds like the issue you're experiencing may be related to how Grafana handles graph rendering, specifically the axis scaling logic. The best project for this issue appears to be the **DataViz project** since it focuses on data visualization aspects including graphing and axis display decisions.

Could you please provide a screenshot or any additional details regarding the configuration of the Soft Min setting? This information would be very helpful for the team to reproduce and address the issue.

Thank you!

**Comment by moxious** [comment] 2024-02-26 09:15
**Summary**: The issue describes a problem in Grafana 9.3.2 where setting a Soft Min on the Y-axis of a disk space free graph with a slow-changing data set leaves insufficient top margin, causing the graph line to nearly clip off, challenging visibility.

**Closed** 2024-09-27 10:41 UTC
