### ISSUE TITLE
grafana dashboard: ad-hoc filter not properly escaping forward slash

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#402] opened 2024-09-04 08:22 UTC
### What happened?

When using an ad-hoc filter with an elasticsearch datasource, the `/` character is not properly escaped. This causes strange results to appear, because `/` is used as the delimiter in lucene regex queries. 

For example, using the ad-hoc filter `httpRequest.url.standardizedPath =~ /api/integrations.*` results in the query `httpRequest.url.standardizedPath://api/integrations.*/`. I believe lucene is parsing the query as `httpRequest.url.standardizedPath:// OR api OR /integrations.*/`. That is:

- an empty regex on the httpRequest.url.standardizedPath field

- `api` in any field 

- the regex `integrations.*` in any field

This causes all sorts of undesired results to be returned.

### What did you expect to happen?

the ad-hoc filter `httpRequest.url.standardizedPath =~ /api/integrations.*` should result in a query like `httpRequest.url.standardizedPath:/\/api\/integrations.*/`, which lucene should parse into a single regex `\/api\/integrations.*` matching against the httpRequest.url.standardizedPath field.

### Did this work before?

I just started using the elasticsearch datasource yesterday, and had never used the ad-hoc filter before today, so I have no idea what behavior they had in the past.

### How do we reproduce it?

1. Create a dashboard with [an ad-hoc filter](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-ad-hoc-filters)

2. Add a panel that uses an elasticsearch data source

3. In the ad-hoc filter, attempt to enter a regex that uses the `/` character

4. Open the query inspector on your panel and confirm that the `/` character in your regex has not been escaped.

### Is the bug inside a dashboard panel?

This isn't really a problem with the dashboard panel, I think it's in the datasource. I'll add this field if requested.

### Environment (with versions)?

Grafana: v11.2.0-73830 (8d98c9eba7)

OS: macos 14.6

Browser: Chrome Version 127.0.6533.89 (Official Build) (arm64)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

elasticsearch 1.0.0

**Comment by tonypowa** [comment] 2024-09-04 08:22
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#91582

**Comment by moxious** [comment] 2024-09-04 08:23
Hi @tonypowa, thanks for bringing this up. It appears that the issue is related to handling ad-hoc filters in Grafana with an Elasticsearch datasource. This seems to be an issue best addressed by the **Grafana Metrics project**, as they handle queries and interactions with time-series databases such as Elasticsearch. I'm tagging this issue for their attention. Meanwhile, as a workaround, consider manually escaping the forward slashes in your regex filter.

**Comment by moxious** [comment] 2024-09-04 08:23
**Summary**: Issue 402 on Grafana's GitHub reports a problem with ad-hoc filters in Grafana dashboards not properly escaping the forward slash when used with Elasticsearch data sources, leading to incorrect query parsing and unexpected results.

**Comment by moxious** [comment] 2024-09-04 08:23
**Elaboration**:


Thank you for submitting a well-detailed issue report concerning the ad-hoc filter escaping behavior with the Elasticsearch data source in Grafana. The details you've provided, including steps to reproduce and the environment where the issue is occurring, are quite comprehensive. 

Before we proceed to address this issue, there's just a bit more information that would be helpful to fully understand and diagnose the problem:

1. Could you please provide a screenshot of the issue as observed in the Grafana query inspector? This can often give additional context that may be crucial for troubleshooting.

2. Have you tried any workarounds or code modifications that partially or fully resolved the issue for you? If so, could you share the changes you made or the steps you took?

3. Is there any additional error log output in your browser's developer console or in the backend logs that could be relevant to this issue? If yes, kindly include it in your response.

4. Could you confirm whether you have tried explicitly escaping the forward slashes in your input (e.g., using `//api//integrations.*` instead of `/api/integrations.*`), and what the outcome was?

Your collaboration on these points will greatly assist us in pinpointing the cause of the problem and finding a solution that can be implemented in future releases.

Looking forward to your response, and thank you again for reaching out!

**Closed** 2024-09-27 10:40 UTC
