### ISSUE TITLE
Grafana HA: memberlist Failed to Join

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#247] opened 2024-02-09 12:39 UTC
### What happened?

Grafana in HA mode tries to join "old" PODs IP

```

level=debug memberlist="2024/01/13 17:19:05 [DEBUG] memberlist: Failed to join 10.92.6.162:9094: dial tcp 10.92.6.162:9094: i/o timeout\n"

level=debug memberlist="2024/01/13 17:18:55 [DEBUG] memberlist: Failed to join 10.92.7.29:9094: dial tcp 10.92.7.29:9094: i/o timeout\n"

```

### What did you expect to happen?

Grafana should do a retry to resolve current IPs of the headless service

### Did this work before?

N/A

### How do we reproduce it?

1. Installing Grafana helm chart

```

- name: grafana

 version: "7.1.0"

 repository: "https://grafana.github.io/helm-charts"

```

values.yaml (partially)

```

grafana:

 replicas: 2

 headlessService: true

 grafana.ini:

 database:

 type: postgres

 ...

 unified_alerting:

 enabled: true

 ha_peers: grafana-headless.grafana:9094

 ha_listen_address: ${POD_IP}:9094

 ha_advertise_address: ${POD_IP}:9094



 # https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/

 envValueFrom:

 POD_IP:

 fieldRef:

 fieldPath: status.podIP

```

2. Getting EP of the Headless service

```

kubectl get ep

grafana-headless 10.92.6.162:9094,10.92.7.29:9094

```

3. Restart PODs:

`kubectl rollout restart deploy/grafana`

4. Checking Headless service:

```

kubectl get ep

grafana-headless 10.92.2.73:9094,10.92.9.5:9094

```

5. Checking logs

```

level=debug memberlist="2024/01/13 17:19:05 [DEBUG] memberlist: Failed to join 10.92.6.162:9094: dial tcp 10.92.6.162:9094: i/o timeout\n"

level=debug memberlist="2024/01/13 17:18:55 [DEBUG] memberlist: Failed to join 10.92.7.29:9094: dial tcp 10.92.7.29:9094: i/o timeout\n"

```

Grafana is trying to join IPs, which were used by the "old" pods (before rollout restart)

### Environment (with versions)?

Grafana: v10.2.3 (1e84fede54)

Helm 7.1.0

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment] 2024-02-09 12:39
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80507

**Comment by moxious** [comment] 2024-02-09 12:40
**Summary**: The issue describes a problem in Grafana's high-availability mode where it fails to join 'old' pod IPs rather than resolving the current IPs of the headless service, especially after a pod restart. The user suggests that Grafana should retry to resolve the current IPs to maintain HA functionality.

**Comment by moxious** [comment] 2024-02-09 12:40
**Elaboration**:


Thank you very much for your detailed report, tonypowa! It's clear that you've put in effort to document the Grafana HA issue you're experiencing. There are just a couple of additional details that could help in troubleshooting this further:

1. Could you please provide the Grafana logs **_after_** the restart happens? This could contain clues as to whether Grafana attempts to refresh its peer list post-restart.

2. Have you configured any liveness or readiness probes for your Grafana pods? If so, can you share the specifics of those configurations? They might be influencing the behavior you're observing.

3. Can you confirm if the issue is consistently reproducible on every restart, or if it only happens intermittently?

4. Additionally, are there any network policies or security groups that might be preventing Grafana pods from communicating after the restart? This could be useful to rule out any infrastructure-level issues.

5. Finally, if possible, could you provide the complete `values.yaml` file (with any sensitive information redacted)? This would help to ensure there are no other configuration aspects affecting the behavior.

Once we have this information, we’ll be better equipped to pinpoint the issue. Thanks again for your contribution and for assisting us in improving our high-availability setup!

**Comment by moxious** [comment] 2024-02-09 12:40
Hello @tonypowa, it looks like you're encountering issues with Grafana operating in high availability (HA) mode within a Kubernetes environment. This appears to be related to service discovery and networking when pods are restarted. Given the specifics of the environment and the HA context, I'll be tagging this issue to the **Grafana Operator Experience Squad** as they may be best suited to provide support for Grafana running in Kubernetes with HA configuration. They can also help with the proper memberlist configuration to handle pod IP changes more gracefully.

/tag @GrafanaOperatorExperience

**Closed** 2024-09-27 10:42 UTC
