### ISSUE TITLE
Alerting: Alerts Migrated using API that leverage panel variables do not Migrate the selected variable values

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#230] opened 2024-01-29 16:49 UTC
### What happened?

Some users created Alerts in an old instance of Grafana using the Azure Monitor plugin. They selected the resource using variables such as $subscriptionId, $resourceGroup, and $resource. When they created the alert from this panel, the resource (the variable values) that they selected at that point in time were used in the alert.

Now, I migrate the Alerts pulling the json from the API endpoint /api/v1/provisioning/alert-rules. And I send this json to the new instance using the same API endpoint /api/v1/provisioning/alert-rules. The alert rule is created as expected, however, the values that were selected for those variables are no longer linked. The dashboard & panel that the Alert rule was based on is already migrated and in place with the same Uid and panel Id.

The resulting Alert rule results in an error and cannot function because it does not know the variable values to use.

### What did you expect to happen?

The old selected values for the variables should have been included in the json and should have been applied to the new Alert rule when it was provisioned.

### Did this work before?

The Alert worked as expected with the selected variable values when it was initially created.

### How do we reproduce it?

1.

2.

3.

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Azure Monitor 1.0.0

**Comment by tonypowa** [comment] 2024-01-29 16:49
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80046

**Comment by moxious** [comment] 2024-01-29 16:50
Hi @tonypowa, it seems like the issue you're experiencing is related to the *alerting* functionality, specifically the migration of alert rules that were based on dashboard panels with selected variable values. I believe the best team to address this would be the **Alerting project** as they manage the alerting features within Grafana. Ensure you provide any additional environment details like your Grafana version, as it might help diagnose the issue more efficiently.

/label ~"Alerting project"

**Comment by moxious** [comment] 2024-01-29 16:50
**Summary**: When migrating alerts using the API in Grafana, the selected variable values for alerts created with the Azure Monitor plugin are not preserved, resulting in an error when the alert rule is transferred to a new instance because the necessary variable values are missing.

**Comment by moxious** [comment] 2024-01-29 16:50
**Elaboration**:


Thank you for providing detailed information about the issue you're experiencing with the alert migration in Grafana. To help our team better understand the problem and work towards a resolution, we could use a bit more detail in a few areas:

- Can you confirm if the issue persists with every alert that uses panel variables, or have there been instances where the variables were migrated correctly?
- It would be helpful if you could provide an example of the JSON payload for an alert rule before and after migration. Please ensure to redact any sensitive data before sharing.
- Have you noticed any error messages either in the Grafana UI or logs when the alert rules fail after the migration? If possible, please provide these error messages.
- Can you detail the steps you've taken for the migration process (steps 1, 2, 3, etc.), so we can try to reproduce the issue consistently on our end?
- For the environment information, could you specify the versions of Grafana and OS you are using, and also the browser version if applicable? Knowing the exact environment could be critical in identifying version-specific issues.
- Lastly, since it appears you're using Grafana Cloud, have you contacted Grafana Cloud support for insights or known issue resolutions regarding this migration behavior?

Once we have this additional information, we'll be in a much better position to help solve this problem. Thanks again for reaching out and for your collaboration!

**Closed** 2024-09-27 10:42 UTC
