### ISSUE TITLE
Dashboards: Custom Variables labels don't display when variable mentioned on the url

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#333] opened 2024-04-17 16:04 UTC
### What happened?

when creating a dashboard using custom variables the labels do not display correctly (and then disappear) 

if reloading the url

Here is the initial view of the dashboard:

<img width="472" alt="Screenshot 2024-03-20 at 5 00 12 PM" src="https://github.com/grafana/grafana/assets/71188769/abf8de21-581d-4bd6-92c8-2c8957c7ebcd">

now select "yes" from the drop down:

<img width="472" alt="Screenshot 2024-03-20 at 5 00 58 PM" src="https://github.com/grafana/grafana/assets/71188769/03d040ed-58f2-4485-9483-743023502b7b">

"yes" (the label) is now displayed in the drop down:

<img width="472" alt="Screenshot 2024-03-20 at 5 00 21 PM" src="https://github.com/grafana/grafana/assets/71188769/957244d0-f36c-4d5b-ae8a-39bbac960bc2">

reload the dashboard url

now "oui" (the value) is displayed in the drop down.

<img width="472" alt="Screenshot 2024-03-20 at 5 00 30 PM" src="https://github.com/grafana/grafana/assets/71188769/f09356a4-91e1-4094-a8a5-fa89a95ccd21">

if you select the drop down only the "All" option is available:

<img width="472" alt="Screenshot 2024-03-20 at 5 00 42 PM" src="https://github.com/grafana/grafana/assets/71188769/63db023a-3a4e-4b95-a9e9-1dfd18d9d14a">

### What did you expect to happen?

The drop down at the end of the sequence should contain the expected lables:

<img width="472" alt="Screenshot 2024-03-20 at 5 00 58 PM" src="https://github.com/grafana/grafana/assets/71188769/03d040ed-58f2-4485-9483-743023502b7b">

### Did this work before?

yes, it used to work back in grafana 8

### How do we reproduce it?

1. create a dashboard with this json:

```

{

 "__inputs": [],

 "__elements": {},

 "__requires": [

 {

 "type": "grafana",

 "id": "grafana",

 "name": "Grafana",

 "version": "10.4.0"

 }

 ],

 "annotations": {

 "list": [

 {

 "builtIn": 1,

 "datasource": {

 "type": "grafana",

 "uid": "-- Grafana --"

 },

 "enable": true,

 "hide": true,

 "iconColor": "rgba(0, 211, 255, 1)",

 "name": "Annotations & Alerts",

 "type": "dashboard"

 }

 ]

 },

 "editable": true,

 "fiscalYearStartMonth": 0,

 "graphTooltip": 0,

 "id": null,

 "links": [],

 "panels": [],

 "schemaVersion": 39,

 "tags": [],

 "templating": {

 "list": [

 {

 "allValue": ".*",

 "current": {

 "selected": false,

 "text": "All",

 "value": "$__all"

 },

 "description": "",

 "hide": 0,

 "includeAll": true,

 "multi": false,

 "name": "custom",

 "options": [

 {

 "selected": true,

 "text": "All",

 "value": "$__all"

 },

 {

 "selected": false,

 "text": "yes",

 "value": "oui"

 },

 {

 "selected": false,

 "text": "no",

 "value": "non"

 }

 ],

 "query": "yes : oui, no : non",

 "queryValue": "",

 "skipUrlSync": false,

 "type": "custom"

 }

 ]

 },

 "time": {

 "from": "now-6h",

 "to": "now"

 },

 "timepicker": {},

 "timezone": "browser",

 "title": "custom-var-test",

 "uid": "fdga0pvf4pzi8e",

 "version": 2,

 "weekStart": ""

}

```

2. select `yes` from the custom variable drop down

3. hit reload on the web page

4. notice how the drop down now shows `oui` (the value not the label)

5. also notice how the only option available for selection is `All`

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: Grafana v10.4.0 (03f502a94d)

OS: browser running on Mac Ventura 13.6.4 (22G513)

Browser: Chrome Version 121.0.6167.184 (Official Build) (arm64)

### Grafana platform?

Kubernetes

### Datasource(s)?

none

**Comment by tonypowa** [comment] 2024-04-17 16:04
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#84870

**Comment by moxious** [comment] 2024-04-17 16:05
**Summary**: Custom variable labels in Grafana dashboards are not displayed correctly after a page reload; instead of the expected label, the variable's value is shown, and the only available option is 'All'. Previously functional in Grafana 8, the issue occurs on Grafana v10.4.0.

**Comment by moxious** [comment] 2024-04-17 16:06
Hi @tonypowa! It looks like you're experiencing an issue with dashboard variables in Grafana. As this issue is related to the functionality and display of dashboard variables, I believe it's best suited for the **Dashboards Sharing squad** project. The team responsible for that area of Grafana should be able to address this problem about the variable labels not appearing correctly after page reloads.

**Comment by moxious** [comment] 2024-04-17 16:06
**Elaboration**:


Hello @tonypowa, thank you for the detailed report! Your step-by-step explanation and the screenshots are really helpful to understand the behavior you're experiencing with custom variables in Grafana. As an additional assist, I have a few questions and requests that could aid us in diagnosing and resolving the issue more efficiently:

1. Could you please confirm if there are any console errors in your browser's developer tools when the issue occurs? Errors logged there would be particularly useful to identify any underlying issues.

2. It would be great if you can share a more complete JSON model of the dashboard (if possible), specifically including any panel configuration that may be relevant to the custom variable.

3. Is this behavior consistent across different browsers or browser versions? Additionally, has this been tested in an incognito window or with browser extensions disabled to rule out any interference from them?

4. Given that it used to work back in Grafana 8, are you able to provide the specific version where this functionality broke, in case you have that information? This could help us pinpoint when the regression may have occurred.

5. In the absence of datasource(s), could you confirm whether the issue is unaffected by any particular datasource configuration or if it occurs even with different or no datasource attached?

6. Lastly, if this is happening on a live environment, it might be worth trying to reproduce the issue on a local setup to ensure external factors within the Kubernetes environment aren't influencing the behavior.

Thank you for using Grafana, and for actively participating in the community. Once we have this additional information, we will be better equipped to address the issue more effectively. Looking forward to your response!

**Closed** 2024-09-27 10:41 UTC
