### ISSUE TITLE
Dashboards: 414 Error "Request-URI Too Large" Popups After 11.x Grafana upgrade

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#388] opened 2024-08-16 13:09 UTC
### What happened?

After upgrading Grafana to latest version (from 10.3.3 to 11.1.0), we noticed error popups on some of our dashboards stating "414 Request-URI Too Large". The popup goes away after a few seconds and there are no obvious issues with the dashboards otherwise.

We see corresponding 414 HTTP response logs in Grafana logs. We also see Prometheus request logs to URL `/api/v1/label/.../values?match[...]` (with very long "match" query parameter - truncated in logs), so it appears those long request URLs are what's triggering these errors.

### What did you expect to happen?

No error popups after upgrade.

### Did this work before?

Yes, this issue did not exist before upgrading Grafana version. We confirmed that the issue only exists in the latest version (11.1.0) and not in the previous version (10.3.3) by deploying old and new versions a few times.

### How do we reproduce it?

We don't have exact steps yet - I suspect any dashboard with prometheus datasource with a large number of metrics may be encountering this.

### Environment (with versions)?

Grafana: 11.1.0

OS: MacOS 14.5

Browser: Chrome 126.0.6478.127

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment] 2024-08-16 13:09
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90452

**Comment by moxious** [comment] 2024-08-16 13:10
**Summary**: Following the upgrade of Grafana from version 10.3.3 to 11.1.0, users are encountering '414 Request-URI Too Large' error popups on dashboards with potentially large Prometheus queries, which did not occur in the previous version.

**Comment by moxious** [comment] 2024-08-16 13:11
Hello @tonypowa, it seems like the issue you encountered is related to the data that is being requested from Prometheus by Grafana and the way HTTP requests are handled. Since this started happening after an upgrade and involves interaction with a datasource, I would suggest this issue is best associated with the **Grafana Metrics project**. However, if the issue is specifically with dashboard query URIs being too long causing the 414 error, the **Frontend Platform project** team may also need to be involved to handle URL length limitations on the frontend. For now, let's start with the Grafana Metrics project to evaluate if they can provide insights into handling these longer Prometheus query URLs.

**Comment by moxious** [comment] 2024-08-16 13:11
**Elaboration**:


Hello @tonypowa, thank you for bringing this to our attention with detailed information about the issue following the upgrade of Grafana. However, we need a bit more information to better understand the problem and to find a solution. Could you please help us by answering the following questions and providing additional information? 

- **Error Details**: Could you provide the full error message or a screenshot of the error popup if possible?
- **URL Length**: When you mention long URLs, can you estimate the length or provide an example of how a typical long URL looks like (with sensitive data redacted, if any)?
- **Reproduction Steps**: While exact steps are not yet known, would you be able to provide a minimal example of a dashboard JSON where this issue occurs, or a list of steps that might increase the likelihood of reproducing the error?
- **Comparison Analysis**: Are there any specific panels or queries that lead to this error, or does it happen randomly across different dashboards?
- **Network Information**: Have you been able to inspect the network requests using browser developer tools to see which exact requests are causing the errors?
- **Error Frequency**: How frequently do these 414 errors occur and does it impact the usability or functionality of the dashboards in a noticeable way?

Any extra information that you could provide will be instrumental in diagnosing and resolving this issue. Once again, thank you for your contribution to the community, and we're looking forward to your response.

**Closed** 2024-09-27 10:40 UTC
