### ISSUE TITLE
TEMPO: When there are numerous projects causing an overwhelming number of spans, the dropdown list in the Span Name becomes very slow

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#168] opened 2023-12-20 08:27 UTC
### What happened?

When there are numerous projects causing an overwhelming number of spans, the dropdown list in the Span Name becomes very slow

![image](https://github.com/grafana/grafana/assets/5334156/c15829b9-c60b-4a87-a1b0-f8ec61546d6b)

### What did you expect to happen?

The span name should be associated with the Resource Service Name. Only the span name in the Resource Service Name is displayed.

### Did this work before?

The span name should be associated with the Resource Service Name. Only the span name in the Resource Service Name is displayed.

### How do we reproduce it?

When there are numerous projects causing an overwhelming number of spans, the dropdown list in the Span Name becomes very slow

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.1

OS: linux 

Browser: crhome

### Grafana platform?

None

**Comment by tonypowa** [comment] 2023-12-20 08:27
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78780

**Comment by moxious** [comment] 2023-12-20 08:27
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment] 2023-12-20 08:28
Hi @tonypowa, it sounds like you are experiencing performance issues related to span information within Grafana's tracing UI. This issue seems to be associated with the **Traces & Profiling project** as it pertains to the handling of spans and their naming within a tracing environment. I will go ahead and suggest that this issue be transferred to the **Traces & Profiling project** for further investigation by the appropriate team. 

To the maintainers: If this issue doesn't belong to Traces & Profiling project, please guide it to the correct project or provide further assistance.

**Comment by moxious** [comment] 2023-12-20 08:28
**Triage summary**: Dropdown list in Span Name becomes excessively slow when handling a large number of spans within Tempo datasource. Expected behavior is to associate span names with the Resource Service Name to improve performance.

**Recommended labels**:

area/datasource
datasource/Tempo
type/performance
type/ux

**Comment by moxious** [comment] 2023-12-20 08:29
**Elaboration**:


Hello @tonypowa, thank you for taking the time to report the issue you’re experiencing with Grafana. It's clear that the slow performance of the dropdown list in the Span Name when dealing with a large number of spans is a concern. To better understand the problem and provide a resolution, we need a bit more detail. Here are some questions and requests for additional information: 

- **Performance Metrics**: Could you provide some performance metrics? For example, how long does it take for the dropdown to load or become responsive? 

- **Reproduction Steps**: The steps you've provided are a bit general. Could you describe in detail the steps to reproduce the issue starting from the login to the occurrence of the slow dropdown? This will help us test under similar conditions.

- **Number of Spans**: Can you quantify 'an overwhelming number of spans'? Knowing the specific number or range would help gauge the load.

- **Console Logs and Network Activity**: Could you check the browser developer tools for any errors in the console or unusual network activity when the issue occurs? Screenshots or the log outputs would be particularly useful.

- **Datasource**: You left the datasource response empty. Could you specify which datasources are connected and active when you encounter this slow down? This information is crucial as performance can be datasource-dependent.

- **Grafana instance details**: Is your Grafana instance running on a server or is it a local setup? If possible, sharing details on the server’s specifications or the local setup configuration might help identify resource-related issues.

- **Previous Versions**: Have you experienced this issue in any previous versions of Grafana, or did it only appear after updating to 10.2.1?

Once we have this information, it will be much easier to pinpoint the cause and work towards a suitable fix. Thank you for collaborating with us to improve Grafana!

**Closed** 2024-09-27 10:43 UTC
Labels: area/datasource, datasource/Tempo, type/performance, type/ux
