### ISSUE TITLE
Plugins: ElasticSearch Plugin fails to load (ChunkLoadError)

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#173] opened 2023-12-27 10:12 UTC
### What happened?

Upon creating a new dashboard or visiting an existing dashboard and attempting to view or set an ElasticSearch datasource (ElasticSearch v7.10+) as a panel source, Grafana reports the following error:

`ChunkLoadError: Loading chunk 9897 failed. (missing: https://grafana.domain.obscured/grafana/public/build/elasticsearchPlugin.5bb6e2e766d541747a9d.js)`

This occurs when for any Elastic datasource. Visiting one such datasource configuration page, then returning to attempt to make the panel seems to resolve this loading error, but the error can be consistently reproduced in a new session.

I suspect that this issue is related to issue #21733, resolved by PR #21677.

### What did you expect to happen?

ElasticSearch datasource to load into panel.

### Did this work before?

Unknown when this issue started occurring. Other dashboards using ES datasources have been created for years, without issue in the past. Grafana v 9.2.0 has been in use for some time now.

### How do we reproduce it?

1. View any Elasticsearch datasource first thing after starting a new session

### Environment (with versions)?

Grafana: 9.2.0

OS: RHEL 7 (Grafana server), MacOS (browser/client)

Browser: Firefox, Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

ElasticSearch 5.0.0

**Comment by tonypowa** [comment] 2023-12-27 10:12
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78927

**Comment by moxious** [comment] 2023-12-27 10:13
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment] 2023-12-27 10:14
**Triage summary**: Users encounter a 'ChunkLoadError' when loading an ElasticSearch datasource in Grafana 9.2.0, which seems to be resolved temporarily by visiting the datasource configuration page. The issue is reproducible in new sessions and might be linked to a previously resolved issue (#21733). Further investigation is required to determine the cause and a permanent fix.

**Recommended labels**:

area/plugins
datasource/Elasticsearch
type/regression
needs investigation

**Comment by moxious** [comment] 2023-12-27 10:14
Thank you for reporting the issue with the ElasticSearch Plugin, @tonypowa. Based on the details provided, I am transferring this issue to the **Plugins Platform** project as it is the most relevant team equipped to handle plugin-related problems including loading errors. They can give you more precise guidance or escalate the bug accordingly.

**Comment by moxious** [comment] 2023-12-27 10:14
**Elaboration**:


Hi @tonypowa, 

Thank you for bringing this issue to our attention. It seems like you're encountering a `ChunkLoadError` when attempting to use an ElasticSearch datasource in Grafana. To better assist you and resolve this issue more efficiently, could you please provide us with some additional information?

- Can you confirm if there are any network issues that might be causing the problem? Check the Network tab in your browser's developer tools for any failed requests.
- Have you tried clearing your browser cache or using Grafana in incognito/private mode to see if the issue persists?
- Could you attach any relevant console logs from your browser when the error occurs? This could provide insights into what may be happening during the chunk load failure.
- Is your Grafana setup behind a reverse proxy, load balancer, or any other network component that could affect resource loading?
- Are any ad blockers or browser extensions possibly interfering with Grafana's script loading?
- Have you made any custom changes to Grafana's configuration files or manually modified any files within the installation directory?
- Can you provide steps to reproduce the issue in a clear, step-by-step format from the beginning of a session? This would help in replicating the issue on our end.

Once we have this additional information, we'll be in a much better position to understand the cause and find a resolution.

Looking forward to your response!

**Comment by tonypowa** [comment] 2023-12-27 10:16
great elaboration points

**Closed** 2024-09-27 10:43 UTC
Labels: area/plugins, datasource/Elasticsearch, type/regression, needs investigation
