### ISSUE TITLE
With Grafana 10.4 not able to click on code button under loki(logs)

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#398] opened 2024-08-21 09:12 UTC
With Grafana 10.4 not able to click on **code** button under **loki(logs)**, even after giving correct locator its not interacting with element through automation script

locator - //label[contains(text(),'Code')]

<img width="949" alt="Screenshot 2024-07-25 104334" src="https://github.com/user-attachments/assets/3b96b588-4d98-4e55-ae6d-ffa5ea7a74b5">

**Actual Result**: java.lang.Exception: Exception:element click intercepted 

**(same thing was working earlier with previous grafana version - 10.2 but facing issue after post upgrade to 10.4)**

**Expected Result**: It should be navigated with the locator and perform click on given element

**Environment**: DEV/QA

- Grafana version: 10.4

- Data source type & version: Loki(logs)

- User OS & Browser: Windows 11, Chrome browser

- Automation Framework : Using Selenium framework through java

aged Grafana

### How do we reproduce it?

1. I am unaware if this is reproducible using certain conditions but I have an entire json that lets me reproduce the same

2.

3.

### Is the bug inside a dashboard panel?

NO

### Environment (with versions)?

Grafana: 10.4.1

OS: Windows 11, Version 23 H2

Browser: Chrome Version 127.0.6533.72 (Official Build) (64-bit)

### Grafana platform?

Other

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment] 2024-08-21 09:12
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90921

**Comment by moxious** [comment] 2024-08-21 09:13
**Summary**: User tonypowa is unable to interact with the 'code' button under 'loki(logs)' in Grafana 10.4 through an automation script, facing a 'click intercepted' exception that wasn't present in the previous version (10.2).

**Comment by moxious** [comment] 2024-08-21 09:14
**Elaboration**:


Hello @tonypowa, 

Thank you for reporting the issue with loKI logs in Grafana 10.4. To better understand and address the issue you're facing, could you please provide us with additional information:

1. Can you verify whether the problem occurs consistently across different browsers or is it isolated to Chrome?
2. Could you please provide the specific Selenium version you are using?
3. Are there any console errors in the browser when you attempt to click the **code** button? If so, please share them.
4. Are you able to interact manually with the **code** button in the UI, or is it only via the automation script that the problem occurs?
5. Could you provide a snippet of the automation script you're using, specifically around the step where it fails to interact with the **code** button?
6. If applicable, please share the complete JSON data that you mentioned helps to reproduce the issue.
7. Have you tried using a different locator strategy, perhaps an XPath that does not rely on text() or a CSS selector, to see if that resolves the issue?

Any additional context or steps to reproduce would be immensely helpful in diagnosing and resolving the problem. Screenshots or a video demonstrating the issue might also be beneficial.

Looking forward to your response!

**Comment by moxious** [comment] 2024-08-21 09:14
Hi @tonypowa, this seems like an issue that might be relevant to the **Frontend Platform project**. The code button interaction in the logs panel might have been affected by UI changes in the new Grafana release. I recommend transferring this issue to that project so the appropriate team can investigate this behavior in cooperation with the **Loki** or **Grafana Metrics project** teams if needed since it involves the Loki data source.

/cc @frontend-platform-team

**Closed** 2024-09-27 10:40 UTC
