### ISSUE TITLE
Tempo Data Source: Cannot connect to Azure Storage Account backend when using Managed Identity

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#203] opened 2024-01-16 09:51 UTC
### What happened?

Attempting to connect to Azure Storage Backend when using a Managed Identity (in the same manner as, say Azure Monitor) via Azure Managed Grafana does not work and there does not appear to be any option to enable it. None of the three options (Basic, Forward OAuth, No auth) work, and no documentation exists for how to use such a thing, so an assumption was made that the required permissions were Blob Storage Data Reader for the MI.

Error message states Unable to connect with Tempo (<?xml version="1.0" encoding="utf-8"?><Error><Code>PublicAccessNotPermitted</Code><Message>Public access is not permitted on this storage account. RequestId:<GUID> Time:<blah>Z</Message></Error>). Please check the server logs for more details.

Except the storage account _is_ configured with public access enabled, so my assumption here is that the data source is not leveraging the managed identity.

### What did you expect to happen?

Connection to the storage account should work with a managed identity.

### Did this work before?

Not that I know of.

### How do we reproduce it?

1. Deploy Azure Managed Grafana with Managed Identity.

2. Deploy Storage Account with blob container and ensure managed identity has Storage Blob Data Reader role assigned to it.

3. Deploy Tempo and tell it to write to Azure Storage Backend (btw, this DOES work with a managed identity).

4. Attempt to configure Managed Grafana... quail at the red error box.

### Environment (with versions)?

Grafana: Grafana v10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea)

OS: Managed by MS; 

Browser: Firefox

### Grafana platform?

Other

### Datasource(s)?

Tempo

**Comment by tonypowa** [comment] 2024-01-16 09:51
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79544

**Comment by moxious** [comment] 2024-01-16 09:52
**Summary**: User tonypowa reported an issue where connecting to Azure Storage Backend using a Managed Identity through Azure Managed Grafana fails, despite having public access enabled and appropriate Blob Storage Data Reader permissions set for the Managed Identity. An error message indicates public access is not permitted, but the user confirms public access is configured, suggesting a problem with the data source not leveraging the managed identity correctly. The issue remains open and steps to reproduce the problem are provided.

**Comment by moxious** [comment] 2024-01-16 09:52
Hello @tonypowa, 

It seems like the issue you're experiencing relates to the integration of Grafana with Azure services, specifically using Managed Identities with Tempo data source. It looks like this might be an issue for either the **`Azure Datasources`** project, which handles integrations with Azure services, or potentially the **`Grafana Operator Experience Squad`** if the Managed Grafana service setup and configurations are managed by them.

However, given the context, the **`Azure Datasources`** project would be the most pertinent place for your issue as it pertains to connecting a Grafana instance to Azure storage using Managed Identities.

Could you please provide any additional logs or error messages related to this issue, and confirm whether the environment is a fully managed Azure Grafana instance? This will help the team diagnose the problem more effectively.

**Comment by moxious** [comment] 2024-01-16 09:52
**Elaboration**:


Hi @tonypowa, thank you for bringing this issue to our attention. To address the problem more effectively, we would appreciate a bit more information. Here are a few questions that can help us understand and troubleshoot the issue better:

- Could you attach the detailed server logs around the time the error occurs? This can contain valuable information about the error's context.
- Have you tried any workarounds or steps to troubleshoot the issue on your own? If so, please describe them.
- Can you confirm if the Managed Identity you're using has been assigned the correct roles not just on the Blob Storage, but also on any other relevant Azure resources?
- Is there any network configuration, such as firewall rules or VNET settings, that could be impacting the connection?
- Additionally, can you provide the exact steps or configuration settings you are using when setting up the data source in Grafana? This would help us attempt to reproduce the issue exactly as you see it.

Please include as much detail as possible since this will greatly assist us in diagnosing and resolving the issue. If you can include screenshots or code snippets (make sure there's no sensitive information), that would also be incredibly helpful.

We look forward to your response to resolve the connectivity issue with Azure Storage Account backend using Managed Identity.

**Closed** 2024-09-27 10:43 UTC
