### ISSUE TITLE
With Grafana 10.4 not able to click on code button under loki(logs)

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#396] opened 2024-08-21 09:12 UTC
With Grafana 10.4 not able to click on **code** button under **loki(logs)**, even after giving correct locator its not interacting with element through automation script

locator - //label[contains(text(),'Code')]

<img width="949" alt="Screenshot 2024-07-25 104334" src="https://github.com/user-attachments/assets/3b96b588-4d98-4e55-ae6d-ffa5ea7a74b5">

**Actual Result**: java.lang.Exception: Exception:element click intercepted 

**(same thing was working earlier with previous grafana version - 10.2 but facing issue after post upgrade to 10.4)**

**Expected Result**: It should be navigated with the locator and perform click on given element

**Environment**: DEV/QA

- Grafana version: 10.4

- Data source type & version: Loki(logs)

- User OS & Browser: Windows 11, Chrome browser

- Automation Framework : Using Selenium framework through java

**Comment by tonypowa** [comment] 2024-08-21 09:12
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90921

**Comment by moxious** [comment] 2024-08-21 09:13
**Summary**: The issue is with Grafana 10.4 where the user is unable to click on the 'code' button under 'loki(logs)' through a Selenium automation script, despite the issue not existing in the earlier version 10.2.

**Comment by moxious** [comment] 2024-08-21 09:13
Hi @tonypowa, it seems this issue is related to a specific problem with the Loki data source in Grafana. I would recommend sharing this issue in the **Grafana Loki** repository to ensure the problem is addressed by the team that maintains that part of the software.

**Comment by moxious** [comment] 2024-08-21 09:13
**Elaboration**:


Thank you for reporting the issue you've encountered with Grafana 10.4 and the inability to click the **code** button under Loki (logs) through your automation script. To help us pinpoint the problem and provide a solution, I have a few follow-up questions for you to answer:

- Are you able to manually click on the **code** button without using the automation script, or is the issue present even when performing manual actions?
- Could you provide the version of Selenium and the specific driver (e.g., ChromeDriver) you are using, along with their versions?
- Can you share more details of the exception stack trace? This will be helpful to understand at what point the click is being intercepted.
- Is the issue reproducible on different browsers or on different machines? Have you tried reproducing this on a different setup?
- Please provide the exact steps you follow in your script leading up to the click on the code button. It's often helpful to understand if there’s a specific order of operations that leads to the issue.
- Lastly, have there been any changes to your configuration or the environment post-upgrade that might be influencing this behavior?

Once we have this additional information, we'll be in a better position to further investigate the problem. Thank you for your cooperation!

**Closed** 2024-09-27 10:40 UTC
