### ISSUE TITLE
Visual artifacts on Time series charts with stacked bars

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#260] opened 2024-02-15 09:23 UTC
### What happened?

There is a visual artifact on the time series charts with bars (Graph style) and stacked series (normal stack) that causes some bars with an actual value of 0 to be drawn higher on the Y-axis.

Let's take a look at my Optimal Viewport Percent chart, this is a chart that displays approximately 1600 data points.

![image](https://github.com/grafana/grafana/assets/4516478/bc8872f3-3501-473f-997a-11783469abe4)

As you can see there are a bunch of yellows bars that lead to believe that there are some suboptimal resolutions. However in reality, this corresponds to data points that return 0% for both optimal and subtopmal resolutions. Let's zoom in on the first group of yellow bars:

![image](https://github.com/grafana/grafana/assets/4516478/73390628-35fc-4812-8f60-013e08143f71)

Now we can see that this bunch of data points with 0% values are correctly represented. At this point Grafana is dealing with approximately 160 data points. The following is a sample of the represented values

![image](https://github.com/grafana/grafana/assets/4516478/f4a133e6-5aac-4c08-a587-8815889779e0)

Suboptimal (yellow bars) is always 0%

Going back to the original results set, I noticed that maximizing the chart reduces the amount of visual artifacts but they are still present:

![image](https://github.com/grafana/grafana/assets/4516478/0e0781d7-1605-4b1c-a3ac-fbe20da60562)

All of this leads me to think that this is an issue only present with a "significantly large" amount of results not being properly rendered by Grafana.

### What did you expect to happen?

Yellow bars should be displayed as small dots at the bottom of the Y axis or not even being drawn at all.

### Did this work before?

not that I'm aware

### How do we reproduce it?

1. Create a time series charts with bars and stacked series (Normal)

2. Display two columns of results that share same timestamp and one of the columns always reports 0

### Environment (with versions)?

Grafana: CE 9.4.7

OS: Ubuntu 23.10

Browser: Firefox 119.0.1

### Grafana platform?

Kubernetes

### Datasource(s)?

JSON API: https://grafana.com/grafana/plugins/marcusolsson-json-datasource/

**Comment by tonypowa** [comment] 2024-02-15 09:23
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80897

**Comment by moxious** [comment] 2024-02-15 09:24
**Summary**: The issue describes a visual artifact in Grafana's time series charts with stacked bars, where bars representing a value of 0 are incorrectly drawn higher on the Y-axis, particularly with large data sets. The expected behavior is for these bars to appear as small dots at the bottom or not be drawn at all.

**Comment by moxious** [comment] 2024-02-15 09:24
**Elaboration**:


Thank you for providing detailed information and screenshots on the issue you're facing with the visual artifacts on the Grafana time series charts. In order to help us better diagnose and address the problem, could you please provide a few additional details? Here are some clarifying questions and requests for more information:

1. Can you confirm if the issue persists across different browsers or if it seems to be isolated to Firefox?
2. Could you share whether the behavior is the same when accessing Grafana through a different device or screen resolution?
3. Is it possible for you to provide a minimal dataset that reproduces the issue so we can attempt to replicate it on our end?
4. Have you observed any console errors in the browser’s developer tools when the issue occurs? If so, could you please provide them?
5. Since this issue involves rendering with a large dataset, any additional details about memory usage or performance metrics at the time of the issue might be helpful. Have you noticed any related performance degradation?
6. Lastly, could you check if any Grafana settings or customizations could be influencing the rendering of your charts, especially with regards to stacking and zero values?

Thank you for your cooperation, and we look forward to your response to better assist you with resolving this issue.

**Comment by moxious** [comment] 2024-02-15 09:24
Hi @tonypowa, thanks for providing such a detailed issue report. It looks like this might be related to the rendering of charts within Grafana's frontend. Therefore, I'd suggest that this issue is best associated with the **Frontend Platform project**. The team responsible for frontend development can look into the visual artifact during rendering of stacked time series charts to locate the bug and work on a fix.

Would you be able to provide exact steps or a sample dataset that reproduces the issue? That could greatly assist in diagnosing and resolving the problem swiftly.

**Closed** 2024-09-27 10:42 UTC
