### ISSUE TITLE
Can't connect to OpenSearch Datasource

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#286] opened 2024-03-01 14:49 UTC
### What happened?

After migration to Grafana10 provisioned datasources has stoped working.

Example provisioned datasource

```

 ######################

 # Elasticsearch DB TEST #

 #######################

 - name: "elasticsearch-au-TEST"

 type: elasticsearch

 database: "[preview-]YYYY-MM-DD"

 url: "https://search-logs-hash.us-east-1.es.amazonaws.com/"

 jsonData:

 interval: Daily

 timeField: "time"

 esVersion: "8.0.0" # was 6.0.0 for Grafana8.5

 sigV4Auth: true

 sigV4AuthType: "default"

 sigV4Region: "us-east-1"

```

It's probably not related AWS IAM and network problems, because for version 8.5.* it working fine, with the similar IAM Role

### What did you expect to happen?

Able to connect to OpenSearch

### Did this work before?

Yes it works for 8.5.*

### How do we reproduce it?

1. Setup Grafana 10

2. Provision OpenSearch datasouce from config above

### Environment (with versions)?

Grafana: 10.3.1

OS: dockerhub - grafana/grafana

Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

OpenSearch

**Comment by tonypowa** [comment] 2024-03-01 14:49
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81854

**Comment by moxious** [comment] 2024-03-01 14:50
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue with connecting Grafana 10 to OpenSearch following your migration. We understand that after the update, your previously functional provisioned datasources are experiencing issues. To help us address this problem efficiently, we would need a bit more information. Could you please provide the following details?

- **Error Messages:** Include any error messages you're receiving when trying to connect to the datasource.

- **Logs:** Share relevant excerpts from the Grafana server logs around the time the connection attempt fails, as they may contain useful error details.

- **Configuration Comparison:** Are there any other differences in the datasource configuration between Grafana 8.5 and 10, besides the `esVersion` change?

- **IAM Role Policies:** Ensure that the IAM Role has the necessary permissions. Even though it worked in Grafana 8.5, please verify that permissions haven't changed and are still correct.

- **Network Settings:** Double-check if any network policies or security group settings might be preventing connections from the newer Grafana version.

- **Reproduction on Different Environment:** If possible, try to reproduce the issue in a different environment to rule out specific issues with the current setup.

Attaching screenshots or additional configuration details can also be very helpful.

Please update the issue with this information, and we'll work towards resolving the connectivity problem as soon as possible.

**Comment by moxious** [comment] 2024-03-01 14:50
**Summary**: User 'tonypowa' reports that after upgrading to Grafana 10, provisioned datasources for OpenSearch are no longer working, despite functioning in version 8.5.*. The user provided the configuration details used and specified that the issue is not related to AWS IAM or network problems.

**Comment by moxious** [comment] 2024-03-01 14:50
Hello @tonypowa, it looks like you're encountering an issue related to configuring a datasource which has been provisioned, specifically with OpenSearch integration. I believe the Grafana team responsible for the 'AWS Datasources' project would be the best fit to help you troubleshoot and resolve this connectivity problem after the migration to Grafana 10. I'll tag this issue for their attention.

```suggestion
/team AWS Datasources
```

**Closed** 2024-09-27 10:41 UTC
