### ISSUE TITLE
CloudWatch Logs: StartQuery: InvalidParameterException - 'logGroupIdentifiers' failed to satisfy constraint

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#182] opened 2024-01-03 13:16 UTC
### What happened?

I have a dashboard which contains a variable that is populated with a list of log groups (the result of a query):

![image](https://github.com/grafana/grafana/assets/6376824/9f5ef300-f282-499e-883e-1aec018c74f2)

I have a few panels that use a CloudWatch Log Insights query to display logs. The query uses the above variable to determine which log groups to query:

![image](https://github.com/grafana/grafana/assets/6376824/bb1f4759-057e-40d6-a464-b01856567663)

The problem is that sometimes I get this error from these panels when trying to load the dashboard.

```

logger=context userId=1 orgId=1 uname=admin t=2023-12-06T16:32:52.650430079Z level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to query data: failed to execute log action with subtype: StartQuery: InvalidParameterException: 1 validation error detected: Value '[arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-createAudioEncodingWorker:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-createLinkArtifactWorker:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-createTranscriptionWorker:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-encodeAudioWorker:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-enrichTextWorker:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-generateAudioFromTextWorker:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-initPipeline:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-initPipelineFromTextWorker:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-refreshPipeline:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-transcribeAudioWorker:*|arn:aws:logs:us-east-2:260462628773:log-group:/aws/lambda/api-dev-translateTextWorker:]' at 'logGroupIdentifiers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 2048, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: [\\w#+=/:,.@-]*]" remote_addr=99.232.224.215 traceID=



```

It seems that the logs groups are being merged together into one entry in the `logGroupIdentifiers` parameter of the `StartQuery` AWS API call. The kicker is that this only happens sometimes. Other times the panel loads the data correctly without error. While trying to debug, I checked details of the StartQuery call in CloudTrail and can clearly see that sometimes the `logGroupIdentifiers` parameter is split up correctly, with the array containing individual log group names, as loaded from the dashboard's variables. Other times, the parameter is set to what you see in the error above. I have spent a lot of time trying to figure out how to reproduce this, but haven't found any consistent method, which leads me to think there is some sort of race condition here. One thing to note is that the length of the entry in the error above is not greater than 2048, so I am guessing it doesn't match the regex pattern. Another thing to note is that I have 4 - 5 dashboards, using 3 variables (which all get populated with result of a cloudwatch logs query), and the error seems to only happen with the dashboards associated with one of the variables. The query I am using is attached in a screenshot below.

### What did you expect to happen?

The `logGroupIdentifiers` parameter should be configured set to an array of strings, with each string being the log group name retrieved from the variable. 

### Did this work before?

Not sure, I only recently set up this dashboard and variable.

Here is what my variable's query looks like:

![image](https://github.com/grafana/grafana/assets/6376824/467b4e37-9984-401c-b8e5-1d3e2e418782)

### How do we reproduce it?

Have not found a consistent way to reproduce this behaviour.

### Is the bug inside a dashboard panel?

| Key | Value |

|--|--|

| Panel | logs @ 10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb) |

| Grafana | 10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb) // Open Source |

<details><summary>Panel debug snapshot dashboard</summary>

```json

{

 "panels": [

 {

 "datasource": {

 "type": "grafana",

 "uid": "grafana"

 },

 "gridPos": {

 "h": 13,

 "w": 15,

 "x": 0,

 "y": 0

 },

 "id": 2,

 "options": {

 "showTime": true,

 "showLabels": false,

 "showCommonLabels": false,

 "wrapLogMessage": true,

 "prettifyLogMessage": true,

 "enableLogDetails": true,

 "dedupStrategy": "none",

 "sortOrder": "Descending"

 },

 "targets": [

 {

 "refId": "A",

 "datasource": {

 "type": "grafana",

 "uid": "grafana"

 },

 "queryType": "snapshot",

 "snapshot": []

 }

 ],

 "title": "Reproduced with embedded data",

 "type": "logs"

 },

 {

 "gridPos": {

 "h": 7,

 "w": 9,

 "x": 15,

 "y": 0

 },

 "id": 5,

 "options": {

 "content": "<table width=\"100%\">\n <tr>\n <th width=\"2%\">Panel</th>\n <td >logs @ 10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)</td>\n </tr>\n <tr>\n <th>Queries</th>\n <td>A[cloudwatch]</td>\n </tr>\n \n <tr><th>Data</th><td>Error 0 frames, 0 fields, 0 rows </td></tr>\n \n <tr>\n <th>Grafana</th>\n <td>10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb) // Open Source</td>\n </tr>\n </table>",

 "mode": "html"

 },

 "title": "Debug info",

 "type": "text"

 },

 {

 "id": 6,

 "title": "Original Panel JSON",

 "type": "text",

 "gridPos": {

 "h": 13,

 "w": 9,

 "x": 15,

 "y": 7

 },

 "options": {

 "content": "{\n \"datasource\": {\n \"type\": \"cloudwatch\",\n \"uid\": \"P034F075C744B399F\"\n },\n \"gridPos\": {\n \"h\": 15,\n \"w\": 24,\n \"x\": 0,\n \"y\": 58\n },\n \"id\": 16,\n \"options\": {\n \"showTime\": true,\n \"showLabels\": false,\n \"showCommonLabels\": false,\n \"wrapLogMessage\": true,\n \"prettifyLogMessage\": true,\n \"enableLogDetails\": true,\n \"dedupStrategy\": \"none\",\n \"sortOrder\": \"Descending\"\n },\n \"targets\": [\n {\n \"datasource\": {\n \"type\": \"cloudwatch\",\n \"uid\": \"P034F075C744B399F\"\n },\n \"dimensions\": {\n \"ApiId\": \"iqx18vs7y9\",\n \"Method\": \"POST\",\n \"Resource\": \"/feeds\"\n },\n \"expression\": \"filter logLevel = \\\"error\\\" and raiseAlert = 1\\n| display @timestamp, error, contentId, @logStream, @log, @message\\n| sort @timestamp desc\",\n \"id\": \"\",\n \"label\": \"\",\n \"logGroups\": [\n {\n \"arn\": \"$ContentPipelineLogGroups\",\n \"name\": \"$ContentPipelineLogGroups\"\n }\n ],\n \"matchExact\": false,\n \"metricEditorMode\": 0,\n \"metricName\": \"5xx\",\n \"metricQueryType\": 0,\n \"namespace\": \"AWS/ApiGateway\",\n \"period\": \"\",\n \"queryMode\": \"Logs\",\n \"refId\": \"A\",\n \"region\": \"default\",\n \"sqlExpression\": \"\",\n \"statistic\": \"Sum\",\n \"statsGroups\": []\n }\n ],\n \"title\": \"All Content Pipeline Alerts\",\n \"type\": \"logs\"\n}",

 "mode": "code",

 "code": {

 "language": "json",

 "showLineNumbers": true,

 "showMiniMap": true

 }

 }

 },

 {

 "id": 3,

 "title": "Data from panel above",

 "type": "table",

 "datasource": {

 "type": "datasource",

 "uid": "-- Dashboard --"

 },

 "gridPos": {

 "h": 7,

 "w": 15,

 "x": 0,

 "y": 13

 },

 "options": {

 "showTypeIcons": true

 },

 "targets": [

 {

 "datasource": {

 "type": "datasource",

 "uid": "-- Dashboard --"

 },

 "panelId": 2,

 "withTransforms": true,

 "refId": "A"

 }

 ]

 }

 ],

 "schemaVersion": 37,

 "title": "Debug: All Content Pipeline Alerts // 2023-12-06 11:52:55",

 "tags": [

 "debug",

 "debug-logs"

 ],

 "time": {

 "from": "2023-12-06T16:22:55.183Z",

 "to": "2023-12-06T16:52:55.184Z"

 }

}

```

</details>

### Environment (with versions)?

Grafana: 10.2.2

OS: Mac M2

Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

CloudWatch

**Comment by tonypowa** [comment] 2024-01-03 13:16
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79155

**Comment by moxious** [comment] 2024-01-03 13:16
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment] 2024-01-03 13:17
**Triage summary**: Intermittent 'InvalidParameterException' error from CloudWatch Logs when a dashboard variable containing log group list is used in Log Insights queries. The issue is causing 'logGroupIdentifiers' parameter to exceed constraints or not match the regex pattern occasionally due to potential race condition.

**Recommended labels**:

datasource/CloudWatch
type/bug
area/backend/api
needs investigation

**Comment by moxious** [comment] 2024-01-03 13:17
Hello @tonypowa, this appears to be an issue related to the AWS data source within Grafana, specifically with CloudWatch Logs integration. Therefore, this issue seems best suited for the **AWS Datasources project** which is responsible for handling data source plugins for AWS services. They should be able to investigate the intermittent 'logGroupIdentifiers' error you're encountering with your CloudWatch queries.

**Comment by moxious** [comment] 2024-01-03 13:18
**Elaboration**:


Thank you for providing detailed information about the issue you're experiencing with CloudWatch Logs queries in Grafana. To better assist you in resolving this problem, I have a few questions that can help us understand and reproduce the error more consistently. Could you please provide answers to the following questions?

1. **Variable Configuration**: Can you share the configuration of the variable that is causing issues? Specifically, the query you are using to populate this variable and any filters or regex patterns applied to it.

2. **Panel JSON**: The debug information you've shared contains a lot of valuable configuration details, but it would be helpful to have the exact JSON configuration of one of the problematic panels. Could you provide the JSON configuration of the panel where this error occurs?

3. **Conditions of the Error**: Since you mentioned that error occurs 'sometimes,' have you observed any patterns such as the time of day, the specific log groups queried, or the number of log groups returned by the variable that might correlate with the occurrence of the error?

4. **Value Formatting**: How are the values from the variable passed to the CloudWatch Logs query? Are there any custom formatting or transformation applied before being used in the `logGroupIdentifiers` parameter?

5. **Grafana Logs**: Can you provide relevant Grafana server logs during the time the error occurs? This might have helpful information that can indicate what might be going wrong.

6. **Variable Refresh Settings**: How is the variable configured to refresh? Is it set to refresh on dashboard load, time range change, or manually? There might be a relation between the refresh mechanism and the race condition you suspected.

7. **Browser Network Activity**: Have you inspected browser network activity to see the exact requests made when the issue occurs? Sometimes, the way the browser handles requests can give a clue about intermittent issues.

8. **Steps Taken**: Besides trying to reproduce the issue consistently, have you taken any specific steps that seemed to have affected the frequency or nature of the issue? For example, increasing Grafana server resources, modifying the dashboard’s queries, or changing settings in AWS.

Once we have a bit more data on any of these fronts, we'll be in a better position to help diagnose and hopefully resolve the issue.

**Closed** 2024-09-27 10:43 UTC
Labels: type/bug, area/backend/api, datasource/CloudWatch, needs investigation
