### ISSUE TITLE
Influx datasource for user with viewer permission error

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#327] opened 2024-04-11 14:53 UTC
### What happened?

Since around 16h our influx 2.x datasource shows up a lot of errors.

Users with only viewer permission are not able to load data resulting in a data source error, while users with editor or admin permission everything still works fine.

We didn't change anything on our system

### What did you expect to happen?

Dashboards with InfluxDB datasource also works for users with Viewer permission

### Did this work before?

Yes before everything worked as expected

### How do we reproduce it?

1. Access a Dashboard with a user with viewer permission

2. See error message: "InfluxDB returned error:"

3.

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: Grafana v11.0.0-67977 (0e7c0d25fe)

OS: Ubuntu 22.04

Browser: Firefox and Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB 2.7

**Comment by tonypowa** [comment] 2024-04-11 14:53
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#84459

**Comment by moxious** [comment] 2024-04-11 14:54
**Summary**: Users with viewer permissions are experiencing errors when trying to load data from InfluxDB 2.x data source on Grafana, despite not having made any changes to the system. The issue, currently open, is affecting Grafana Cloud users since the error does not occur for users with editor or admin rights.

**Comment by moxious** [comment] 2024-04-11 14:54
Hi @tonypowa, it seems like the issue you're experiencing is related to the InfluxDB datasource permissions within Grafana Cloud. I'd recommend transferring this issue to the **AWS Datasources project** as it's the closest match given that InfluxDB is one of the data sources handled there, and even though InfluxDB isn't strictly AWS, the team managing AWS Datasources has experience with datasource permission issues.

**Comment by moxious** [comment] 2024-04-11 14:54
**Elaboration**:


### Thank you for submitting the issue, @tonypowa!

It appears that you’re encountering permission issues with InfluxDB as a datasource in Grafana. To better assist you in resolving this, there are a few additional pieces of information that could help us investigate further:

1. **Error Details:** Can you provide the exact error message received when a user with viewer permissions tries to access a dashboard? A screenshot of the error might also be helpful.

2. **Panel Query Information:** Is the issue occurring on a specific panel within the dashboard, or is it widespread across all panels that use the InfluxDB datasource? If it's a specific panel, sharing the query that the panel is using might give us some insights.

3. **User Permissions:** Were there any recent changes in the user permissions settings either in Grafana or the InfluxDB instance that might have affected viewer permissions?

4. **Logs:** Can you check the logs for both InfluxDB and Grafana around the time the issue started? Look specifically for errors related to permissions or datasource access.

5. **Reproduction Steps:** The reproduction step '3.' seems to be incomplete. Could you please provide the full steps you take after seeing the error message to identify the behavior of the issue?

6. **Configurations:** Have you checked the InfluxDB datasource configuration in Grafana to ensure that the viewer settings have not been inadvertently adjusted?

7. **Update Status:** Have there been any recent updates to Grafana or your InfluxDB instance prior to when this issue first appeared?

Once you have gathered this information, please update the issue with your findings. This will help us pinpoint the issue more precisely and provide you with a solution.

Thank you for your collaboration!

**Closed** 2024-09-27 10:41 UTC
