### ISSUE TITLE
Variables do not work with Filter data by values Transformation

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#178] opened 2024-01-02 14:41 UTC
### What happened?

I created a brand new dashboard, added some variables of query and custom type. Then created a panel with some data I'd like to filter. I added the Filter data by values transformation but it does not show the variable dropdown to select from, nor does it work if I type the variable in manually like $variableName.

### What did you expect to happen?

I expected to see a variable dropdown within the value field of the Filter data by values transformation as shown in the video here https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-2/#use-dashboard-variables-in-transformations. Typing $ or Ctrl + Space should show the dropdown but they do not.

### Did this work before?

No this is a new experimental feature added in Grafana 10.2

### How do we reproduce it?

1. Update to the latest version of Grafana (10.2.2 at the time of writing)

2. Create a new dashboard

3. Add one query or custom type variable (My variable options are numbers not strings)

4. Create a panel and query some data which can be filtered

5. Add the Filter data by values transformation 

6. Add a condition on a number type field

7. Set the match field to equal

8. Within the value field type $ or press Ctrl + Space and observe there is no menu shown

9. Type the variable manually ($variableName) into the value field and observe that this does not work

### Is the bug inside a dashboard panel?

The bug is affecting dashboard panel transformations

### Environment (with versions)?

Grafana: v10.2.2

OS: Zorin OS 16 (Based on Ubuntu)

Browser: Google Chrome v119 

### Grafana platform?

Docker

**Comment by tonypowa** [comment] 2024-01-02 14:41
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79118

**Comment by moxious** [comment] 2024-01-02 14:41
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment] 2024-01-02 14:42
**Triage summary**: The issue describes a failure to use variables within the 'Filter data by values' dashboard panel transformation in Grafana 10.2.2, where the expected variable dropdown doesn't show and manually entered variables do not work.

**Recommended labels**:

area/dashboard/templating
area/transformations
type/feature-request
needs investigation

**Comment by moxious** [comment] 2024-01-02 14:42
Hi @tonypowa,

It seems like you have encountered an issue with dashboard panel transformations and the use of variables in Grafana. This issue might be best addressed by the **Frontend Platform project** since it involves user interface aspects and the integration of transformations with dashboard variables.

I suggest forwarding this issue to the Frontend Platform project team to get their insights on this behavior. Meanwhile, you might also want to check if there are any existing open issues related to this in the project's issue tracker.

Thanks for reporting this and providing clear steps to reproduce the issue!

**Comment by moxious** [comment] 2024-01-02 14:43
**Elaboration**:


Hi @tonypowa, thanks for reporting this issue with the 'Filter data by values' transformation and variables in Grafana. To help our team dig into this issue more effectively, could you please provide the following additional information? 

- **Datasource Type:** You mentioned querying some data. Could you specify which datasource you are using? This can sometimes impact how variables are interpreted.

- **Variable Configuration Snapshot:** It would be helpful to see the configuration settings for the variables you've created. If possible, could you include a screenshot of your variable settings or the JSON model of the variable?

- **Panel JSON Model:** Sometimes the issue lies in the specific setup of the panel. If you could export and share the JSON model of the problematic panel, that would be extremely helpful for troubleshooting.

- **Error Messages:** Are there any error messages displayed either in the panel itself or in the browser console when attempting to use a variable in the transformation?

- **Step-by-Step Reproduction:** We appreciate the steps you've provided. If you noticed any particular nuances or specifics when the issue occurs, please include them.

- **Screenshots or Recordings:** Visuals can be incredibly helpful. If you could provide screenshots or a video recording of the process you're undertaking, especially showing the dropdown not appearing and the failure when manually entering the variable, that would help us identify the problem more quickly.

Once we have this additional information, we'll be in a much stronger position to understand the issue and work towards a fix. Thank you for your contribution to enhancing Grafana!

**Closed** 2024-09-27 10:43 UTC
Labels: area/dashboard/templating, area/transformations, type/feature-request, needs investigation
