### ISSUE TITLE
Dashlane autofilling on data sources "Org" and "Token" Fields

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#347] opened 2024-05-30 14:36 UTC
Every time I go and even look at the Home > Connections > Data sources > "Influx DB" for 2.0 using token the Organization and Token fields are auto-populated by Dashlane.

 

I have been working through the whole Dashlane documentation to remove the specific fields from their autofill however it seems it always comes back or is specific to a page which always seems to change.

Meaning it starts happening again!

Interestingly enough when Dashlane does autofill, (as soon as the page has loaded) it has already saved this bogus data, so even if I exit the page immediately, it has still been saved!

This of course breaks everything. Then I have to re-input the Org again, and find (or create a new) token and save. (every time again telling dashlane to NOT FILL ON THIS FIELD that never saves - perhaps that is a dashlane problem)

I am wondering if you could perhaps add (autocomplete="off") or find a way that these fields never get attacked by Dashlane/Lastpass or Chrome at all?

![image](https://github.com/grafana/grafana/assets/50091235/5058d321-ef61-40cc-99ba-30041ea270fd)

**Comment by tonypowa** [comment] 2024-05-30 14:36
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#87783

**Comment by moxious** [comment] 2024-05-30 14:37
Hello @tonypowa, thanks for reporting this issue. It seems like this problem would be best addressed by the **Frontend Platform project**. Adding `autocomplete='off'` to input fields is something that the frontend development team can look into to improve interaction with password management tools like Dashlane. 

I'll label this issue for their attention, and they can assess the best steps to take to prevent auto-filling issues in future updates.

**Comment by moxious** [comment] 2024-05-30 14:37
**Summary**: Issue 347 remains OPEN where Dashlane autofills the 'Org' and 'Token' fields on the 'Influx DB' data sources page in Grafana, despite attempts to disable autofill using Dashlane documentation. The user requests implementation of 'autocomplete="off"' or another solution to prevent autofill by password managers.

**Comment by moxious** [comment] 2024-05-30 14:38
**Elaboration**:


Hello @tonypowa, thank you for reaching out with your issue regarding the autofill behavior of Dashlane on the Organization and Token fields within your Influx DB data source configuration in Grafana. 

To help us further understand and address the issue, it would be great if you could provide the following additional information:

1. **Grafana Version:** Please specify the version of Grafana you are currently using. 
2. **Browser and Version:** Could you let us know the browser and version where you are experiencing this problem? 
3. **Extensions and Version:** It would be helpful to know the version of Dashlane you are using, and whether you have similar issues with other browser extensions like LastPass or Chrome’s built-in password manager. 
4. **Steps to Reproduce:** If possible, please provide a detailed step-by-step process on how to reproduce this issue, starting from logging in to Grafana until the autofill occurs.
5. **Confirmation of Issue Persistency:** Can you confirm if you've tried using Grafana in incognito mode or after disabling Dashlane to ensure that the issue is consistent and not a one-off occurrence?
6. **Error Logs:** If there are any error logs within the browser console when the issue occurs, sharing them could be beneficial for diagnosis.
7. **Past Issues or Workarounds:** Have you seen similar issues reported with other services or fields within Grafana? If you have encountered a workaround that temporarily solves the issue, please let us know.

A screenshot showing the autofill happening would also be very handy if the one you provided is not displaying correctly; it appears the link might be broken or incomplete. If you could re-upload or provide a correct link to the screenshot, it would go a long way in helping us visualize the problem.

With this information, we'll be better equipped to troubleshoot the issue and find a good solution. Thank you for your cooperation, and we appreciate your contribution to the community!

**Closed** 2024-09-27 10:41 UTC
