### ISSUE TITLE
[User permissions according to dashboards]

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#211] opened 2024-01-16 11:28 UTC
### What happened?

I have created multiple users in an organization I want to achieve particular user will see particular dashboard only.

But in my case all the users are able to see all the dashboards in that organization.

According to official document I have follow the steps.

### What did you expect to happen?

Not all the users will able to see all the dashboards in that organization only a particular user which i want will have that permission to see that dashboard.

Added the permissions in dashboard also but not working.

### Did this work before?

No, this is not working at all.

### How do we reproduce it?

- Sign in to Grafana as an organization administrator.

- In the left-side menu, click Dashboards.

- Hover your mouse cursor over a folder and click Go to folder.

- Click the Permissions tab, and then click Add a permission.

- In the Add Permission For dropdown menu, select User, Service Account, Team, or Role.

- Select the user, team, or role.

- Select the permission and click Save.

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment] 2024-01-16 11:28
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79638

**Comment by moxious** [comment] 2024-01-16 11:29
**Summary**: The issue, opened by tonypowa, describes a problem where all users within an organization can see all dashboards, despite attempts to restrict access according to the official documentation. The expected behavior is that only specified users should have permission to view particular dashboards, but these permissions are not working as intended.

**Comment by moxious** [comment] 2024-01-16 11:30
**Elaboration**:


### Request for Additional Information

Hello @tonypowa, thank you for reaching out to the community about the issue you are encountering with user permissions and dashboards in Grafana. It looks like you've encountered a problem where despite configuring permissions according to the official documentation, all users still have access to all dashboards.

To help us better understand and address the issue, could you please provide some additional information?

1. **Grafana Version:** What version of Grafana are you using?
2. **Operating System:** What operating system is the Grafana instance running on?
3. **Browser:** Which browser version was used to set up these permissions? Could this issue be browser-specific?
4. **Explicit Steps:** Can you confirm that the steps mentioned in the official documentation completely match the steps you've taken? If there are any deviations, please list them.
5. **Screenshots:** Could you include screenshots of the permission settings for the dashboards in question?
6. **User and Team Settings:** Are there any specific user roles or team configurations that might be affecting the permission settings?
7. **Logs:** Are there any logs available from Grafana that show what happens when you try to modify these permissions?
8. **Repeatable Issue:** Is this issue consistent across all dashboards and users, or have you noticed it only in certain situations?
9. **Error Messages:** Are you receiving any error messages, either in the UI or in Grafana logs, when you attempt to set the permissions?

Providing these details will be a great help in diagnosing the problem. If there's any other context or relevant configuration you believe could be impacting this behavior, please include that as well.

Looking forward to your response to better assist you in resolving this issue.

**Comment by tonypowa** [comment] 2024-01-16 11:35
it was great to see that the main elaboration points that i came up with coincide with the bot's!

**Closed** 2024-09-27 10:43 UTC
