### ISSUE TITLE
Alerting: PendingPeriod is wrong for Prometheus Datasource AlertRules

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#353] opened 2024-06-03 13:33 UTC
### What happened?

When viewing Prometheus (VictoriaMetrics) Alert rules in Grafana UI (11.0), "Pending Period" shows "0s" for all alert rules, which seems to be a default value, not the actual duration on the alert rule. I've verified the alert rules api response included the correct `duration` (in seconds, ie `900`) 

### What did you expect to happen?

The actual alert `for`/`duration` to be displayed, or a `not available` or similar instead of a incorrect value. 

### Did this work before?

No.

### How do we reproduce it?

1. Define some alert rules in a prometheus datasource

2. Add Datasource to Grafana

3. View Alert rules

### Environment (with versions)?

Grafana: 11.0

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment] 2024-06-03 13:33
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#87937

**Comment by moxious** [comment] 2024-06-03 13:34
**Summary**: User tonypowa reports a bug in Grafana UI version 11.0 where the 'Pending Period' for Prometheus (VictoriaMetrics) Alert rules incorrectly displays '0s' instead of the actual duration. The issue occurs when viewing the alert rules, with expectations for it to show the actual duration or a placeholder if not available. The issue is reproducible and has never worked before.

**Comment by moxious** [comment] 2024-06-03 13:34
**Elaboration**:


Hi @tonypowa,

Thank you for reporting the issue with the pending period display for Prometheus Datasource AlertRules in Grafana. To help us better understand and address the issue, could you please provide some additional information?

1. Could you confirm the version of Prometheus you are using?
2. Are you able to provide the raw JSON response from the alert rules API where the correct `duration` is included? This could help us verify the parsing of the duration on the Grafana side.
3. Is there any error in the Grafana server logs or browser console when you view the Alert rules? If yes, kindly provide the log messages.
4. In the steps to reproduce, you mentioned defining some alert rules in a Prometheus datasource. Could you provide an example of an alert rule definition where you encounter this problem?
5. Have you made any customization to Grafana or Prometheus regarding alerting features, or are you using default settings?
6. As it is running on Kubernetes, have you checked for any related issues with the configuration maps used for rule definitions, if applicable?
7. Lastly, a screenshot of the Grafana UI where the 'Pending Period' wrongly displays '0s' would be incredibly helpful for visual context.

Additional context or configuration files (with sensitive information redacted) can be very useful in diagnosing the problem more effectively. Thank you for your collaboration, and we look forward to resolving this issue together.

Best regards,
The Grafana Team

**Comment by moxious** [comment] 2024-06-03 13:35
Hi @tonypowa, thank you for reporting this issue. It seems your concern is related to the handling of Prometheus datasource alert rules within the Grafana UI. This appears to be an issue more aligned with the **Alerting project** as it deals with the representation and functionality of alert rules. I'm going to tag this issue to the Alerting team so they can take a closer look.

```markdown
/label alerting
/assign @alerting-team
```

**Closed** 2024-09-27 10:40 UTC
