### ISSUE TITLE
Grafana Dashboards: No title being displayed on the grafana dashboard list, shows "Missing Title" as the title 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#397] opened 2024-08-21 09:12 UTC
### What happened?

 Upgraded my Amazon Managed Grafana from version 9.4.7 to 10.4.1 and observed that one of my dashboard had no title. When tried to click on it within the folder view, it did not open. When I tried using the list view , I observed that the same dashboard had the "Missing Title" as the title and it was accessible. 

 

<img width="1340" alt="image" src="https://github.com/user-attachments/assets/363de25d-0a35-4f69-87a7-a17e948c9762">

### What did you expect to happen?

I expected that the dashboard would display the original title instead of the " Missing Title" .

Also if there is already a value against the dashboard title it should display the same.

![image](https://github.com/user-attachments/assets/ab7784fe-5117-4ef0-a073-9758870a6873)

### Did this work before?

This worked fine within the Grafana Version 9.4.7 in Amazon Managed Grafana

### How do we reproduce it?

1. I am unaware if this is reproducible using certain conditions but I have an entire json that lets me reproduce the same

2.

3.

### Is the bug inside a dashboard panel?

NO

### Environment (with versions)?

Grafana: 10.4.1

OS: Windows 11, Version 23 H2

Browser: Chrome Version 127.0.6533.72 (Official Build) (64-bit)

### Grafana platform?

Other

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment] 2024-08-21 09:12
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90933

**Comment by moxious** [comment] 2024-08-21 09:13
**Summary**: After upgrading Amazon Managed Grafana from version 9.4.7 to 10.4.1, a dashboard is showing 'Missing Title' instead of its original title and is not accessible from the folder view but can be accessed in list view; issue persists despite title existing, and reproduction steps are unclear.

**Comment by moxious** [comment] 2024-08-21 09:13
Hi @tonypowa, it seems like the issue you're experiencing is related to dashboards within Amazon Managed Grafana. Since this involves the managed service context and potentially dashboard metadata handling during the version upgrade, this should likely be associated with the **Hosted Grafana project**. A team member from that project will be able to assist you further with this specific behavior after an upgrade in the managed environment. 

Thank you for reporting, and please include the JSON of the dashboard if it doesn't contain sensitive data, as it might help in reproducing the issue!

```json
// Optionally include your dashboard JSON here if possible.
```

**Comment by moxious** [comment] 2024-08-21 09:14
**Elaboration**:


Hello @tonypowa, thank you for reaching out with this issue regarding missing dashboard titles following an upgrade to Grafana 10.4.1. It's concerning to hear that one of your dashboards is not displaying its title correctly, and I'd like to gather a bit more information to help diagnose and resolve the issue. Could you please provide the following details?

- Could you confirm if the issue is occurring with just one specific dashboard or with multiple dashboards since the upgrade?
- Is it possible for you to check if there were any errors or warnings in the Grafana server logs around the time you noticed the issue with the missing titles?
- If convenient, would you be able to share a sanitized version of the dashboard JSON that is causing the issue? This will be instrumental in trying to reproduce the issue.
- Could you also check and share the permissions set on the dashboard that is having the issue? Sometimes permission issues might cause unexpected behavior in displaying dashboard components.

A screenshot of the issue is very helpful, thank you for including that. However, in addition to that, if you could provide a step-by-step instruction (if possible) to reproduce the issue or any specific configuration that might be relevant, that would be greatly appreciated.

Once you provide some of this information, it should give us a better basis to identify the root cause of the 'Missing Title' issue and how to address it. We appreciate your contribution to improving Grafana. Looking forward to your response!

**Closed** 2024-09-27 10:40 UTC
