### ISSUE TITLE
Provisioning: Dashboard provider folderUid not working

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#140] opened 2023-12-05 16:37 UTC
### What happened?

I'm using the panel 'Dashboard list', which previously, on version 10.1.1, had the option to select all folders. Now that I updated to the newest version (10.2.2), I need to specify a folder, which would be fine with me but now that I added the uid to my provisioned folder, it doesn't get set for the selected folder. Instead a random uid is assigned and since the dashboard is also privisioned, every time I restart grafana the default 'Dashboard' folder is selected instead of my own.

### What did you expect to happen?

Folder get's assigned defined uid and can be used in a provisioned dashboard.

### Did this work before?

Yes, at least until version 10.1.1. I checked, if the uid specified in the privisioning yaml get's assigned to the folder by selecting the folder instead of all in the 'Dashboard list' panel.

### How do we reproduce it?

1. Use the following yaml for the provisioning:

```yaml

apiVersion: 1

providers:

 - name: monitoring

 folder: 'Monitoring'

 folderUid: monitoring

 type: file

 options:

 path: /monitoring-dashboards/

```

2. Add the panel 'Dashboard list'

3. Select the folder 'Monitoring'

4. Look in the panel json and search for '"folderUID": '

5. See the random uid

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.2

OS: docker/kubernetes

Browser: chrome

### Grafana platform?

Docker

**Comment by moxious** [comment] 2023-12-05 16:38
**Triage summary**: After upgrading to Grafana version 10.2.2, the 'Dashboard list' panel no longer allows selecting all folders and setting a 'folderUid' for provisioning does not get acknowledged, leading to random UIDs being assigned on Grafana restarts. This functionality worked as expected in version 10.1.1.

**Recommended labels**:

area/configuration
area/backend/api
type/regression

**Comment by moxious** [comment] 2023-12-05 16:39
Hi @tonypowa, it looks like this issue pertains to a problem with provisioning dashboards in Grafana, which could be related to the Backend platform project. However, considering the provisioning directly involves interaction with dashboards, the **Dashboards Sharing squad** might be the most relevant team to address the issue with the  property not working as expected. 

The Dashboards Sharing squad specializes in sharing and provisioning features of Grafana dashboards, so they would likely have the necessary expertise to investigate and resolve this behavior. 

/tag @dashboards-sharing-squad

**Meta**:

**Comment by moxious** [comment] 2023-12-05 16:39
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hey @tonypowa, it seems like you've encountered quite the folder fiasco with Grafana! While the team is untangling this UID unpleasantry, here's something to lighten the mood. 😄👨‍💻

**Knock, knock.**
_Who’s there?_
**Control Freak.**
_Control Freak who?_
**Okay, now you say, 'Control Freak who?'**

In the meantime, have you tried reverting back to the old configuration structure temporarily, or confirming if the 'folderUid' is indeed compatible with provisioned dashboards in the release notes for 10.2.2? Also, if you can provide a minimal reproduction (such as a stripped-down docker-compose file), that might help identify if this is an issue with Grafana itself or specific to your environment.

We'll keep an eye out for your updates so we can stay in sync, even if currently, Grafana isn't playing in harmony with your uids!

**Meta**:

**Comment by moxious** [comment] 2023-12-05 16:39
**Elaboration**: 
  
Hello @tonypowa, thank you for reaching out with this issue. I would like to gather more information to better understand the problem you’re experiencing. Could you please provide the following details? 

1. Can you confirm if you have any logs that indicate an error when Grafana tries to use the specified  during startup or when provisioning dashboards?

2. After the provisioning with the specified , have you verified whether the folder has the correct UID set in Grafana's UI or API?

3. Is the  you're trying to set a unique identifier that hasn't been used by other folders in your Grafana instance?

4. Could you please provide the snippet of the dashboard JSON where the  is specified? This can help in identifying if there's any issue with the dashboard JSON format.

5. Besides the  not being set as expected, are there any other issues or unusual behaviors you are observing within Grafana since the update?

6. Have you made any other changes to your configuration files that could potentially affect the provisioning process?

Providing these additional details will help us in pinpointing the issue and resolving it efficiently. Thank you for collaborating with us to improve the project!

**Meta**:

**Closed** 2024-09-27 10:44 UTC
Labels: area/backend/api, area/configuration, type/regression
