### ISSUE TITLE
Variables: Constant variables should not become part of URL query parameters

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#301] opened 2024-03-14 09:45 UTC
### What happened?

When creating one custom variable that is exposed to the UI to switch between values, and another hidden constant variable, then the constant variable also becomes part of the URL when switching between values of the custom variable. This means that it is not guaranteed that the dashboard is always using the current value of the hidden constant variable when links are shared that include URL query parameters.

### What did you expect to happen?

All hidden variables should never become part of URLs.

### Did this work before?

No.

### How do we reproduce it?

1. Create a variable of type "Custom" with two values 1 and 2.

2. Create a variable of type "Constant" with value "foo"

3. Save the dashboard

4. Switch the value for the custom variable

5. Observe that the URL now contains the hidden variable as well

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.1

OS: Linux

Browser: Edge

### Grafana platform?

Other

**Comment by tonypowa** [comment] 2024-03-14 09:45
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82682

**Comment by moxious** [comment] 2024-03-14 09:46
**Summary**: The issue #301, opened by tonypowa, reports that hidden constant variables in Grafana are incorrectly being included in URL query parameters when switching between custom variable values, which may lead to improper use of dashboard links.

**Comment by moxious** [comment] 2024-03-14 09:46
**Elaboration**:


### Further Information Required

Thank you for submitting this issue, @tonypowa! Your report helps us improve the product for everyone. It sounds like you're experiencing unexpected behavior with hidden constant variables appearing in URL parameters within Grafana. To better understand and address the issue, we’ll need some additional information.

- Could you confirm whether any additional configuration options have been set for the constant variable, aside from its value?
- Is this behavior observed consistently across different browsers, or is it specific to Microsoft Edge? Have you tried reproducing the issue on browsers like Chrome or Firefox?
- Are there any URL encoding settings or proxies that could be affecting how the URL is being composed?
- Do you have any plugins or scripts running that might interfere with how the UI handles variable data and URL generation?
- Could you please provide us with a screenshot of the issue, particularly showing the URL with the constant variable included after switching the value of the custom variable?
- Lastly, if there are any error messages or relevant logs displayed in the console of your browser or in Grafana's server logs, it would be extremely helpful to have those as well.

The steps you have provided seem clear, but having this additional context will help us reproduce the issue accurately. Once we have this information, we’ll be better positioned to identify the cause and find a resolution.

Looking forward to your response, and thank you for your cooperation in resolving this issue!

**Comment by moxious** [comment] 2024-03-14 09:46
Hi @tonypowa, it appears that the issue you described pertains to the handling of variables within Grafana dashboards. Based on your description, I believe that the **Frontend Platform project** would be the most relevant for this issue, as it seems to involve the behavior of the dashboard UI and how variables are integrated into the URL structure of the Grafana UI.

**Closed** 2024-09-27 10:41 UTC
