### ISSUE TITLE
Dashboards: Adhoc filter does not work with backslash

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#111] opened 2023-11-28 14:28 UTC
### What happened?

When I click on "filter for value" on a text value that contains backslash, it shows nothing. If I escape that backslash in ad hoc filter, then the data is displayed.

Almost the same thing was fixed earlier [here](https://github.com/grafana/grafana/issues/72008), only there were double quotes

https://github.com/grafana/grafana/assets/82204499/3ed14060-1f03-4658-847f-15a676c33043

### What did you expect to happen?

The data should be filtered, including the value with backslash

### Did this work before?

it definitely worked on version 9.20

### How do we reproduce it?

1. There must be a value with text data that contains backslash

2. On the table panel, click "filter for value" or "filter out value".

### Environment (with versions)?

Grafana: 10.2.1

OS: Linux Debian

Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Elasticsearch 7.17.15

**Comment by moxious** [comment] 2023-11-28 16:13
**Triage summary**: The issue is with adhoc filters on dashboards not correctly handling text values with backslashes in Grafana 10.2.1, using Elasticsearch as the datasource. The expected behavior is for the filter to work with backslashes, as it did in previous version 9.20.

**Recommended labels**:

area/dashboard
type/bug
datasource/Elasticsearch
needs investigation

**Comment by moxious** [comment] 2023-11-28 16:13
**Elaboration**: 
  
Hello @tonypowa, thank you for reporting the issue with adhoc filtering on dashboards in Grafana. It sounds like there may be an inconsistency or a regression with text values that contain backslashes. To help us investigate and address this issue efficiently, could you please provide us with a bit more information? 

Here are a few follow-up questions and requests:

1. Could you attach a screenshot or a short video that demonstrates the issue? The link provided seems to be incomplete or broken, as it leads to a  page.

2. When you say it worked in version 9.20, to clarify, was the behavior exactly the same (text values with single backslashes without needing to escape), or were there any other steps or configurations that were different?

3. Is there a specific query or panel setting that triggers this behavior, or does it happen consistently with any text value containing a backslash?

4. Could you provide the exact steps or a sample query that we can use to reproduce the issue on our end, assuming we set up a similar environment?

5. Did you modify any default settings for Grafana or Elasticsearch that might be relevant to this issue?

6. Are there any errors shown in the Grafana server logs or in the browser console when the issue occurs?

The more specific details you can provide, the better we will be able to reproduce and diagnose the problem. Again, we appreciate your contribution to the Grafana community and look forward to resolving this issue.

Thank you for your time and assistance!

**Meta**:

**Comment by pavel-mokrushin** [comment] 2023-12-11 08:00
1. https://github.com/moxious/triage/assets/82204499/4ddc9e22-df16-48e3-8c0c-20f29fb8ace6
2. No additional actions were required. Everything worked by default
3. This works with any text value.
4. You just need any backslash value in elasticsearch
5. The settings have not changed
6. There are no errors

**Closed** 2023-12-11 12:39 UTC
Labels: type/bug, area/dashboard, datasource/Elasticsearch, needs investigation
