### ISSUE TITLE
alerting: creating a new alert returns an instant-vector even if time series and range are selected

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#251] opened 2024-02-14 13:45 UTC
### What happened?

When I create a new alert (from a panel or from the alerting overview), the query directly returns a reduced value. The query shows a table with values. The reduce expression prints a "this function is not needed". 

Switching between type "Range" and "Instant" does not change this, neither does changing format to "time series". 

Only newly created alerts are affected. I still have previously created alerts that return a time series and even when I add a second query to them, I can switch between Instant and Range and the behavior is as expexted showing a time series when the type is "instant". 

### What did you expect to happen?

range giving me a time range

### Did this work before?

It worked definitely before the last major release. Not sure when afterwards it broke, as I am not daily adding new alerts. I noticed the new behavior maybe some weeks ago (and we have auto-updates on the grafana repo except for major versions). 

### How do we reproduce it?

1. create a new alert

2. check that it is "range"

3. press "run queries" or "preview"

### Is the bug inside a dashboard panel?

export via api/v1/provisioning/alert-rules/export:

 - uid: e985b71a-6df8-4373-8794-c1f58a236113

 title: bugtest

 condition: C

 data:

 - refId: A

 relativeTimeRange:

 from: 600

 to: 0

 datasourceUid: cf6775f7-9e82-40fa-88df-04cc7b7caa67

 model:

 datasource:

 type: prometheus

 uid: cf6775f7-9e82-40fa-88df-04cc7b7caa67

 editorMode: code

 expr: system_load1{job="monitoring"}

 hide: false

 instant: false

 intervalMs: 1000

 legendFormat: __auto

 maxDataPoints: 43200

 range: true

 refId: A

 - refId: B

 relativeTimeRange:

 from: 600

 to: 0

 datasourceUid: __expr__

 model:

 conditions:

 - evaluator:

 params: []

 type: gt

 operator:

 type: and

 query:

 params:

 - B

 reducer:

 params: []

 type: last

 type: query

 datasource:

 type: __expr__

 uid: __expr__

 expression: A

 intervalMs: 1000

 maxDataPoints: 43200

 reducer: last

 refId: B

 type: reduce

 - refId: C

 relativeTimeRange:

 from: 600

 to: 0

 datasourceUid: __expr__

 model:

 conditions:

 - evaluator:

 params:

 - 1000

 type: gt

 operator:

 type: and

 query:

 params:

 - C

 reducer:

 params: []

 type: last

 type: query

 datasource:

 type: __expr__

 uid: __expr__

 expression: B

 intervalMs: 1000

 maxDataPoints: 43200

 refId: C

 type: threshold

 noDataState: NoData

 execErrState: Error

 for: 5m

 annotations: {}

 labels:

 service: k

 isPaused: false

### Environment (with versions)?

Grafana: 10.2.3

OS: Debian stable

Browser: Firefox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment] 2024-02-14 13:45
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80724

**Comment by moxious** [comment] 2024-02-14 13:46
**Summary**: Issue #251 remains OPEN. User tonypowa reports that creating a new alert in Grafana instantly returns a reduced value instead of expected time series, despite selecting 'Range' type and configuring for 'time series' format. This behavior differs from older alerts and appears after the last major release. Steps to reproduce and affected environment details are provided.

**Comment by moxious** [comment] 2024-02-14 13:46
Hi @tonypowa, it looks like your issue is related to alerting behavior with range vectors and time series in Grafana. The best fit for this issue seems to be the **Alerting project** since it's directly related to the alerting functionalities within Grafana and potentially a regression from a previous release.

**Comment by moxious** [comment] 2024-02-14 13:46
**Elaboration**:


Hi @tonypowa, thank you for the detailed report! To better help us understand and address the issue you're experiencing, could you please provide additional information and clarify a few points? Here are some questions and requests to assist the engineers investigating your issue:

1. Could you share some screenshots of the alert configuration that is returning an instant-vector instead of the expected time series? This visual aid can be crucial in identifying any UI discrepancies or misconfigurations.

2. Have you noticed any specific configurations or conditions under which this behavior occurs consistently, or does it seem to happen randomly across different alerts?

3. Can you confirm if this issue persists across different browsers or after clearing browser cache? This might help rule out any browser-specific quirks or caching issues.

4. Would you be able to provide the Grafana server logs around the time when you create or edit an alert and experience this issue? Server logs could contain errors or anomalies that might be relevant.

5. As you mentioned that new alerts are affected but older ones return a time series correctly, can you confirm if there are any differences in the setup between the old alerts and the new ones beyond their creation time?

6. Lastly, it could be very helpful if you're able to reliably reproduce this issue, to provide us with step-by-step instructions on how to replicate the problem using a minimal example.

Understanding the context and having details like these can make all the difference in quickly identifying and resolving the problem. Thank you for collaborating with us on this!

**Closed** 2024-09-27 10:42 UTC
