### ISSUE TITLE
Time series graph does not show data

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#209] opened 2024-01-16 11:19 UTC
### What happened?

If gradient mode is "Scheme" the data may not be displayed after loading the dashboard

### What did you expect to happen?

graphs should be displayed

### Did this work before?

idk

### How do we reproduce it?

1. Create time series graph and set gradient mode to "Scheme"

2. Create query with data and without data

3. Reload dashboard with query without data

4. With dashboard variables select query with data - time series graph should be empty

### Environment (with versions)?

Grafana: 10.2.2

OS: windows 10

Browser: latest Chrome & Firefox 

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Postgresql 16 + timescaledb

**Comment by tonypowa** [comment] 2024-01-16 11:19
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79617

**Comment by moxious** [comment] 2024-01-16 11:20
**Summary**: Issue #209: A time series graph set to gradient mode 'Scheme' in Grafana 10.2.2 fails to display data after loading the dashboard, even when selecting a query that includes data. Reproduction steps and affected environments are provided.

**Comment by moxious** [comment] 2024-01-16 11:21
Hi @tonypowa, it sounds like the issue you're experiencing is related to the rendering of time series graphs within Grafana dashboards. This seems to be most closely associated with the **Frontend Platform project**, as it involves the visualization of data on the grafana user interface. I am going to label this issue for the Frontend team to take a look. Meanwhile, can you confirm if this occurs consistently across different time series panels or only in specific cases? Thanks! 

/project Frontend Platform project

**Comment by moxious** [comment] 2024-01-16 11:21
**Elaboration**:


Hi @tonypowa, thanks for reporting the issue with the time series graph. To help us understand the problem better and address it effectively, could you please provide some additional information?

- When you say "data may not be displayed," is there any error message, or is the graph simply blank?
- Can you confirm if this behavior occurs consistently every time you follow the reproduction steps, or does it happen intermittently?
- Is there any specific configuration in Grafana or Postgresql + timescaledb that you think might be relevant to this issue?
- Since you're unsure if this worked before, could you please try an earlier version of Grafana (if possible) to see if the issue persists there?
- Could you attach a screenshot of the graph not displaying the data even when it's supposed to be available?
- Regarding the bug being inside a dashboard panel, could you clarify whether the issue is with a particular panel or if it's more widespread?

A detailed step-by-step reproduction scenario, along with any screenshots or error logs, would greatly help us in diagnosing and resolving the issue. If you are able to share your dashboard JSON, it could also provide valuable insight.

Thank you for your cooperation, and we look forward to getting more information to help resolve this problem!

**Closed** 2024-09-27 10:43 UTC
