### ISSUE TITLE
alert-rules: view in explore forward does not work for 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#229] opened 2024-01-29 16:43 UTC
### What happened?

Seems like the `View in Explorer` forwarding when checking an alert rule is broken for non-default data sources. If you check the forwarded explorer page, always the default data source is selected. The same behavior happens for the Loki data source. 

### What did you expect to happen?

I expect the right data source to be selected with the corresponding query.

### Did this work before?

Not sure.

### How do we reproduce it?

1. Configure non-default Google Cloud Monitoring data source.

2. Create an alert rule with a simple query on the newly added data source.

3. Check the `View in Explorer` forward button. 

### Environment (with versions)?

Grafana: v10.0.3

OS: Ubuntu 22.04

Browser: Google Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Google Cloud Monitoring, Loki

**Comment by tonypowa** [comment] 2024-01-29 16:43
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79995

**Comment by moxious** [comment] 2024-01-29 16:44
**Summary**: Issue #229 is open and describes a bug where the 'View in Explorer' feature in Grafana v10.0.3 does not correctly forward to the selected non-default data source, such as Google Cloud Monitoring or Loki, but defaults to the pre-configured default data source instead.

**Comment by moxious** [comment] 2024-01-29 16:44
**Elaboration**:


Thank you for taking the time to submit this issue, tonypowa. To help us better understand and address the problem with the `View in Explorer` button behavior, could you please provide a few additional details? It would be valuable to know the following: 

- **Additional replication steps**: Can you confirm if there are any specific configurations or steps taken within the data sources Impacting the behavior?
- **Screenshots or recording**: A visual aid such as a screenshot or a short video recording displaying the issue could be very helpful for us to pinpoint the UI elements in question.
- **Console logs**: Are there any error messages in the browser console when you attempt to use the `View in Explorer` button? You can typically open the browser console with `Ctrl+Shift+J` or `Cmd+Option+J` on Chrome.
- **Network requests**: Could you inspect the network requests made when clicking the `View in Explorer` button? This is available under the Network tab in the browser's developer tools (`F12`). Look for any failed requests or requests not posting the expected data source.
- **Grafana logs**: If possible, the Grafana server logs around the time when the issue occurs might reveal additional clues.

Once we have this information, it will be much easier to reproduce and troubleshoot the issue effectively. Thank you for your collaboration!

**Comment by moxious** [comment] 2024-01-29 16:44
Hi @tonypowa, it looks like the issue you're experiencing is related to the way alert rules integrate with exploratory views within Grafana. Considering the problem is related to forwarding and selecting data sources in alerting functionalities, this issue seems most relevant to the **Alerting project**. The team involved with alerting would be the best to handle this concern as it relates to how alert rules interact with different data sources in the UI. Please ensure this issue is transferred to the Alerting project for appropriate handling. 

To help speed up the process, can you please confirm that this issue persists after clearing the cache and trying in an incognito browser window? Additionally, it would be helpful if you could share any relevant logs from the Grafana server.

**Closed** 2024-09-27 10:42 UTC
