### ISSUE TITLE
Grafana: Auto-provisioning creates "ghost" folders.

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#299] opened 2024-03-14 09:41 UTC
### What happened?

My company uses Grafana's provisioning system to conveniently add new dashboards and categorize them in folders. However, when new folders for an organization are specified, a "ghost folder" is created: It exists in the `dashboard` table, but not in the `folder` table, and thus can neither be deleted, nor viewed, nor used.

Example:

Provisioning: https://github.com/senpro-it/grafana-provisioning/blob/main/dashboards/sonicwall.yaml#L11-L17

```

grafana=# select id,title,is_folder from dashboard where org_id=10;

 id | title | is_folder

-----+-------------------------+-----------

 372 | Raspberry Pi Foundation | t

 376 | REDDOXX GmbH | t

 373 | Monitoring Agent | f

 377 | REDDOXX Appliance | f

 409 | SonicWall (Firewall) | f

 412 | SonicWall Inc. | t

 321 | Synology (DSM) | f

 290 | Backup & Replication | f

 244 | Windows (Server) | f

 332 | vSphere | f

 320 | Synology Inc. | t

 331 | VMware, Inc. | t

 144 | Microsoft Corporation | t

 181 | Veeam Software Group | t

(14 rows)



grafana=# delete from dashboard where id=412;

DELETE 1

grafana=# select id,title from folder where org_id=10;

 id | title

-------+-------------------------

 1258 | VMware, Inc.

 56035 | Raspberry Pi Foundation

 56491 | REDDOXX GmbH

 341 | Synology Inc.

 144 | Microsoft Corporation

 181 | Veeam Software Group

(6 rows)

```

(The delete statement inbetween is actually another part of this; the "ghost folder" immediately re-appears. This was me testing it.)

### What did you expect to happen?

I expected to see a new proper folder being created, allowing for the organization of dashboards through provisioning files.

### Did this work before?

It seems so. I only started in this company fairly recently but have upgraded grafana a few times by now in our k3s cluster; considering that my collegues have used the same procedure for well over a year now and it only recently started being an issue, I am quite positive that it did work before. Unfortunately, I can not pin down a version number. But, let's just assume the version in active release during september of 2023; this is when I had just started here.

### How do we reproduce it?

1. Take out a copy of the dashboards here: https://github.com/senpro-it/grafana-provisioning/blob/main/dashboards

2. Make sure to have an org with id=10

3. Attempt to provision the SonicWall related files.

4. You should now get a dashboard and a folder. However, the folder is a lie.

5. Check your database, you should now have the "SonicWall Inc." folder marked as such in `dashboard` - but _not_ in `folder`.

6. Attempt to delete the ghostly folder; you will be met with a "Not found" message.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 10.3.1

OS: NixOS 23.11

Browser: Firefox

### Grafana platform?

Kubernetes

### Datasource(s)?

Not relevant

**Comment by tonypowa** [comment] 2024-03-14 09:41
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82510

**Comment by moxious** [comment] 2024-03-14 09:43
**Elaboration**:


Thank you for submitting a great issue! Your detailed report outlines the unexpected behavior with Grafana's auto-provisioning, offers comprehensive reproduction steps, and includes both the environment details and the problematic behavior experienced. The provided SQL snippets and references to the provisioning files are quite helpful for understanding the issue.

However, to assist you further, could you please also include the following information?

1. **Grafana logs**: Could you provide relevant Grafana server logs around the time the issue occurs? This could offer more insights into what might be going wrong during the provisioning process.

2. **Provisioning configuration**: Is the aforementioned YAML the exact provisioning configuration used? If not, could you provide the provisioning files you're using, making sure to redact any sensitive information?

3. **Screenshots**: It may also be beneficial to attach some screenshots showing the 'ghost' folders in the Grafana UI, as these visual evidences can sometimes provide additional context.

4. **Previous Grafana version**: If possible, would you be able to identify the last known working version of Grafana where this issue was not present? Understanding which version introduced the problem can help in pinpointing the root cause.

5. **Upgrade path**: Can you detail the upgrade path you took for Grafana in your k3s cluster? This might reveal any migration or compatibility issues that arose from version changes.

Your collaboration is vital to resolving this, and we appreciate your time in providing these additional details!

**Comment by moxious** [comment] 2024-03-14 09:43
Hello @tonypowa, it sounds like you're encountering an issue with the provisioning system of Grafana which relates to dashboard folders management. This seems to be related to the core functionality of how Grafana interacts with dashboards and folders on a backend level. Therefore, I suggest this issue might be best addressed by the **Backend platform project** team. They could assist further in diagnosing the issue with ghost folders during the provisioning process.

**Closed** 2024-09-27 10:41 UTC
