### ISSUE TITLE
Dashboards: Ad hoc filter variable doesn't reflect metrics from selected time range 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#322] opened 2024-04-11 14:23 UTC
### What happened?

On a dashboard with a Prometheus datasource that last received a given metrics label more than 24h ago, an ad hoc variable fails to list that label even when the selected time range (e.g. now->2d) should contain metrics with that label.

A query template variable for the same label includes results for the selected time range.

### What did you expect to happen?

I expected to see the ad-hoc drop-down reflect the labels for the selected time range.

I can induce the expected behavior temporarily by going to the explorer and extending the time range for the prometheus datasource I am targeting to the desired duration (e.g. now->2d). Then when I navigate back to the dashboard the ad hoc drop-down correctly includes the expected metrics label. If I refresh the page or open the link in another tab, though, the problem recurs.

### Did this work before?

No.

### How do we reproduce it?

1. Target a datasource with labeled metrics that are older than x (where x is greater than whatever arbitrary default the ad-hoc query is using). For me that happens to be 24h, but someone with more insight into how the query is being composed could probably figure out the exact number. 

2. Select a time range on a dashboard with an ad hoc query variable that should include the labeled metric

4. Note that the labeled metric fails to appear as an option in the ad hoc query drop-down

5. Bonus: Add a query variable for the same label and notice that it does populate for the selected time range

### Environment (with versions)?

Grafana: v10.4.0 (03f502a94d)

OS: macos 14.3

Browser: chrome 122.0.6261.111

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment] 2024-04-11 14:23
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#84135

**Comment by moxious** [comment] 2024-04-11 14:24
**Summary**: The issue describes a problem where an ad hoc filter variable on a Grafana dashboard does not show metrics labels from the selected time range for a Prometheus datasource, while a query template variable does. The expected behavior of reflecting the selected time range in the ad hoc drop-down is only temporary and can be induced by manually extending the time range in the explorer.

**Comment by moxious** [comment] 2024-04-11 14:25
**Elaboration**:


Hi @tonypowa, thank you for reporting the issue with ad hoc filter variables on Grafana dashboards! 🛠️ It sounds like there might be an issue with how the ad hoc filters are querying the Prometheus data source. To better assist with this issue, we would appreciate a few additional details which can help us in reproducing and diagnosing the problem more accurately. Here's what would help us move forward: 

1. **Prometheus Query Details**: Could you please provide the exact query you are using for the ad hoc variable, as well as for the query template variable? Understanding how these queries differ might help identify the cause of the discrepancy.

2. **Dashboard Settings**: Are there any particular settings on the dashboard that might be influencing the ad hoc query results, such as template variable configurations, time overrides, or others that you might have set up?

3. **Steps To Reproduce**: You've provided helpful steps, but any additional context or clarification on these steps will ensure we're completely aligned. For example, details about the specific labeled metrics would be useful.

4. **Screenshots**: If possible, could you attach screenshots of the ad hoc filter variable and the query variable with the populated result, alongside screenshots illustrating the issue when the labeled metric fails to appear? This might help visualize the issue better.

5. **Error Logs**: Are there any relevant error messages or logs in the Grafana server or browser console when the issue occurs?

6. **Grafana Configuration**: Are there any specific configurations or settings in your Grafana instance that might be related to the issue (e.g., limit on query results, caching settings)?

7. **Prometheus Configuration**: How is your Prometheus data source configured in Grafana? Are there any special settings or overrides that could be impacting this?

Once we have this additional information, we’ll have a much clearer pathway to uncovering the root cause of your issue. Thanks again for your contribution, and we're looking forward to resolving this for you! 🌟

**Closed** 2024-09-27 10:41 UTC
