### ISSUE TITLE
Node Graph: How to render based on Kusto data?

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#266] opened 2024-02-19 13:22 UTC
### What happened?

Trying to get a basic node graph to render based on a Kusto query. This dataset should be conformant with [the documented graph data model](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/node-graph/#data-api):

```Kusto

let nodes = datatable(id:string, subtitle:string)

[

 "north", "mainland",

 "east", "island",

 "south", "mainland",

 "west", "island"

];

let edges = datatable(id:string, source:string, target:string, subtitle:string)

[

 "b1", "north", "east", "bridge",

 "b2", "north", "west", "ped bridge",

 "b3", "north", "west", "bridge",

 "b4", "east", "west", "overpass",

 "b5", "east", "south", "bridge",

 "b6", "west", "south", "bridge",

 "b7", "west", "south", "bridge"

];

nodes | as nodes;

edges | as edges

```

I get only a stack of nodes rendered:

<img width="135" alt="image" src="https://github.com/grafana/grafana/assets/11893897/ca18652b-0cab-4850-a878-e315fdd2e5fd">

If I comment out the `nodes | as nodes` line, I get a graph! This tells me Grafana cannot pick up both result tables from Kusto. (The `as` operator names each datatable in the result.) Seems like a bug.

### What did you expect to happen?

With the Node Graph visualization, I expect a graph. :-)

### Did this work before?

N/a

### How do we reproduce it?

[above]

### Is the bug inside a dashboard panel?

| Key | Value |

|--|--|

| Panel | nodeGraph @ 10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea) |

| Grafana | 10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea) // Pro |

<details><summary>Panel debug snapshot dashboard</summary>

```json

{

 "panels": [

 {

 "type": "nodeGraph",

 "title": "Reproduced with embedded data",

 "gridPos": {

 "h": 13,

 "w": 15,

 "x": 0,

 "y": 0

 },

 "datasource": {

 "type": "grafana",

 "uid": "grafana"

 },

 "id": 2,

 "targets": [

 {

 "refId": "A",

 "datasource": {

 "type": "grafana",

 "uid": "grafana"

 },

 "queryType": "snapshot",

 "snapshot": [

 {

 "schema": {

 "refId": "A",

 "meta": {

 "typeVersion": [

 0,

 0

 ],

 "custom": {

 "ColumnTypes": [

 "string",

 "string"

 ]

 },

 "executedQueryString": "let nodes = datatable(id:string, subtitle:string)\r\n[\r\n \"north\", \"mainland\",\r\n \"east\", \"island\",\r\n \"south\", \"mainland\",\r\n \"west\", \"island\"\r\n];\r\nlet edges = datatable(id:string, source:string, target:string, subtitle:string)\r\n[\r\n \"b1\", \"north\", \"east\", \"bridge\",\r\n \"b2\", \"north\", \"west\", \"ped bridge\",\r\n \"b3\", \"north\", \"west\", \"bridge\",\r\n \"b4\", \"east\", \"west\", \"overpass\",\r\n \"b5\", \"east\", \"south\", \"bridge\",\r\n \"b6\", \"west\", \"south\", \"bridge\",\r\n \"b7\", \"west\", \"south\", \"bridge\"\r\n];\r\nnodes | as nodes;\r\nedges | as edges\r\n"

 },

 "fields": [

 {

 "name": "id",

 "type": "string",

 "typeInfo": {

 "frame": "string",

 "nullable": true

 },

 "config": {}

 },

 {

 "name": "subtitle",

 "type": "string",

 "typeInfo": {

 "frame": "string",

 "nullable": true

 },

 "config": {}

 }

 ]

 },

 "data": {

 "values": [

 [

 "north",

 "east",

 "south",

 "west"

 ],

 [

 "mainland",

 "island",

 "mainland",

 "island"

 ]

 ]

 }

 }

 ]

 }

 ]

 },

 {

 "gridPos": {

 "h": 7,

 "w": 9,

 "x": 15,

 "y": 0

 },

 "id": 5,

 "options": {

 "content": "<table width=\"100%\">\n <tr>\n <th width=\"2%\">Panel</th>\n <td >nodeGraph @ 10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea)</td>\n </tr>\n <tr>\n <th>Queries</th>\n <td>A[grafana-azure-data-explorer-datasource]</td>\n </tr>\n \n <tr><th>Data</th><td> 1 frames, 2 fields, 4 rows </td></tr>\n \n <tr>\n <th>Grafana</th>\n <td>10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea) // Pro</td>\n </tr>\n </table>",

 "mode": "html"

 },

 "title": "Debug info",

 "type": "text"

 },

 {

 "id": 6,

 "title": "Original Panel JSON",

 "type": "text",

 "gridPos": {

 "h": 13,

 "w": 9,

 "x": 15,

 "y": 7

 },

 "options": {

 "content": "{\n \"type\": \"nodeGraph\",\n \"title\": \"Panel Title\",\n \"gridPos\": {\n \"x\": 0,\n \"y\": 26,\n \"w\": 12,\n \"h\": 8\n },\n \"datasource\": {\n \"uid\": \"dc429e7c-4bad-403e-913c-95aed3ee0a16\",\n \"type\": \"grafana-azure-data-explorer-datasource\"\n },\n \"id\": 5,\n \"targets\": [\n {\n \"datasource\": {\n \"type\": \"grafana-azure-data-explorer-datasource\",\n \"uid\": \"dc429e7c-4bad-403e-913c-95aed3ee0a16\"\n },\n \"refId\": \"A\",\n \"resultFormat\": \"table\",\n \"database\": \"logs\",\n \"rawMode\": true,\n \"OpenAI\": false,\n \"query\": \"let nodes = datatable(id:string, subtitle:string)\\r\\n[\\r\\n \\\"north\\\", \\\"mainland\\\",\\r\\n \\\"east\\\", \\\"island\\\",\\r\\n \\\"south\\\", \\\"mainland\\\",\\r\\n \\\"west\\\", \\\"island\\\"\\r\\n];\\r\\nlet edges = datatable(id:string, source:string, target:string, subtitle:string)\\r\\n[\\r\\n \\\"b1\\\", \\\"north\\\", \\\"east\\\", \\\"bridge\\\",\\r\\n \\\"b2\\\", \\\"north\\\", \\\"west\\\", \\\"ped bridge\\\",\\r\\n \\\"b3\\\", \\\"north\\\", \\\"west\\\", \\\"bridge\\\",\\r\\n \\\"b4\\\", \\\"east\\\", \\\"west\\\", \\\"overpass\\\",\\r\\n \\\"b5\\\", \\\"east\\\", \\\"south\\\", \\\"bridge\\\",\\r\\n \\\"b6\\\", \\\"west\\\", \\\"south\\\", \\\"bridge\\\",\\r\\n \\\"b7\\\", \\\"west\\\", \\\"south\\\", \\\"bridge\\\"\\r\\n];\\r\\nnodes | as nodes;\\r\\nedges | as edges\\r\\n\"\n }\n ]\n}",

 "mode": "code",

 "code": {

 "language": "json",

 "showLineNumbers": true,

 "showMiniMap": true

 }

 }

 },

 {

 "id": 3,

 "title": "Data from panel above",

 "type": "table",

 "datasource": {

 "type": "datasource",

 "uid": "-- Dashboard --"

 },

 "gridPos": {

 "h": 7,

 "w": 15,

 "x": 0,

 "y": 13

 },

 "options": {

 "showTypeIcons": true

 },

 "targets": [

 {

 "datasource": {

 "type": "datasource",

 "uid": "-- Dashboard --"

 },

 "panelId": 2,

 "withTransforms": true,

 "refId": "A"

 }

 ]

 }

 ],

 "schemaVersion": 37,

 "title": "Debug: Panel Title // 2024-01-21 23:13:12",

 "tags": [

 "debug",

 "debug-nodeGraph"

 ],

 "time": {

 "from": "2024-01-21T17:13:12.314Z",

 "to": "2024-01-21T23:13:12.314Z"

 }

}

```

</details>

### Environment (with versions)?

Grafana: Azure Managed Grafana

Browser: Edge

### Grafana platform?

Other

### Datasource(s)?

Kusto

**Comment by tonypowa** [comment] 2024-02-19 13:22
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80944

**Comment by moxious** [comment] 2024-02-19 13:23
**Summary**: User tonypowa is experiencing an issue with rendering a node graph visualization in Grafana based on Kusto query results. While they expect a graph to render, they instead receive a stack of nodes unless they comment out a specific line in their Kusto query. This suggests a possible bug with Grafana's handling of multiple result tables from Kusto.

**Comment by moxious** [comment] 2024-02-19 13:23
Hi @tonypowa! It sounds like you're experiencing a potential bug in how Grafana is handling multi-result queries from a Kusto datasource for a Node Graph panel. This interaction seems specific to Grafana's display and data interpretation functionalities. Consequently, the **Grafana Frontend Platform project** would be the appropriate team to investigate this issue as they are responsible for the UI components and visualizations like the Node Graph panel. Make sure your Grafana platform and the panel plugin are on the latest versions, as this may also be resolved in a more recent release.

**Comment by moxious** [comment] 2024-02-19 13:24
**Elaboration**:


Thank you for providing a detailed issue report with your Kusto query, the unexpected behavior you are experiencing, and the panel debug snapshot. However, to help us better diagnose the problem, could you please provide a few additional pieces of information?

1. **Kusto Query Response:** Could you include the raw response from the Kusto query? This would help us understand the structure of the data returned from the database.

2. **Configuration Details:** It seems that Grafana is not picking up both result tables. Could you provide more details on how you have configured the Node Graph panel to consume the tables named `nodes` and `edges`? Is there any custom configuration that might be affecting the rendering?

3. **Steps Executed:** Are there any other steps you've performed between running the query and trying to render the graph that might be relevant to this issue?

4. **Error Logs:** Are there any error messages in the browser's console or Grafana logs that occur when attempting to render the graph?

5. **Comparison:** If possible, can you provide a comparison screenshot showing how the graph looks when commenting out the `nodes | as nodes;` line versus how it looks with the line included?

6. **Grafana Version:** Could you confirm if the issue is happening on the latest version of Grafana, in case there has been an update since the creation of this issue?

By providing this additional information, we can ensure a more precise diagnosis of the issue. Thank you for your cooperation!

**Closed** 2024-09-27 10:42 UTC
