### ISSUE TITLE
Panel issues starting with iOS 17.2 (mobile devices)

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#186] opened 2024-01-03 13:45 UTC
### What happened?

Starting with iOS 17.2, dashboards are running into issues. Some panels are not displayed until the user start scrolling. 

### What did you expect to happen?

All panels are visible immediately after loading a dashboard on mobiles.

### Did this work before?

YES, issue is starting with iOS 17.2. Reproduced on Safari. Issue also reproducible on browsers which are using Apples WebKit.

### How do we reproduce it?

1. update iOS to 17.2 RC (public release next week)

2. open a dashboard

3. first panels are missing the most of the time

https://github.com/grafana/grafana/assets/14274103/388e8198-f050-45ae-a7d5-ef07cdbac306

### Environment (with versions)?

Grafana: 10.2.2

OS: Ubuntu Focal

Browser: Safari

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

**Comment by tonypowa** [comment] 2024-01-03 13:45
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79176

**Comment by moxious** [comment] 2024-01-03 13:45
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment] 2024-01-03 13:46
**Triage summary**: Users on iOS 17.2 experience issues where some dashboard panels do not display until scrolling begins. This problem, which affects Safari and other browsers using Apple's WebKit, did not occur in previous iOS versions.

**Recommended labels**:

area/mobile-support
type/regression
datasource/InfluxDB
area/frontend

**Comment by moxious** [comment] 2024-01-03 13:46
Hi @tonypowa, thanks for bringing this to our attention. It looks like the issue you're experiencing pertains to how Grafana dashboards render on iOS devices, which involves both frontend and compatibility aspects. To ensure this gets addressed by the correct team, I'll direct your report to the **Frontend Platform project**. They are equipped to investigate issues related to frontend display, especially for different devices and browsers.

Could you please also provide any console logs or errors that appear when you experience the missing panels? That would assist the team in diagnosing the issue faster.

**Comment by moxious** [comment] 2024-01-03 13:47
**Elaboration**:


Hello @tonypowa! 

Thank you for raising this issue with the mobile compatibility. To help us address it effectively, we'll need a bit more information: 

1. Could you please confirm if the issue persists across all dashboards or if it's specific to a certain configuration or type of panel?
2. Are there any console errors or warnings in the browser developer tools when you encounter the missing panels?
3. You mentioned a link to an asset which seems to be incomplete. Could you please provide a valid link to a screenshot or video recording that illustrates the issue?
4. Have you tried clearing the browser cache or using a private browsing session to see if the issue persists?
5. Can you ascertain whether this issue occurs with browsers on desktop versions (using the same WebKit versions) or is it strictly on mobile iOS 17.2?
6. Lastly, is there any additional configuration or custom CSS/JS that could be impacting the rendering of panels on mobile devices?

Any additional information or steps that could help us reproduce the issue on our end would be greatly appreciated.

Thank you for your collaboration!

**Comment by tonypowa** [comment] 2024-01-03 13:52
could not find the existing issue the support bot is talking about. I guess it's because this is a copy of the same issue in the grafana/grafana repo
great elaboration points though

**Closed** 2024-09-27 10:43 UTC
Labels: area/frontend, area/mobile-support, datasource/InfluxDB, type/regression
