### ISSUE TITLE
Dashboards Grafana - infinite fetching of dashboard data

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#274] opened 2024-02-21 11:53 UTC
### What happened?

After upgrading Grafana as part of OMD package we are facing infinite dashboard loading issues along with data consumption from datasources. 

Please see attached - query tasks just loads tons of data and never stop.

![image](https://github.com/grafana/grafana/assets/68842306/1c37d7a6-ae75-42f1-a10f-d08497480b3c)

### What did you expect to happen?

Dashboard panel should be loaded and fetching stopped once graph is populated

### Did this work before?

Yes, on our main instance of grafana 7.5.13 everything seem to work fine

![image](https://github.com/grafana/grafana/assets/68842306/19cf32d1-5c30-41cc-85ba-ca4e0df347d9)

### How do we reproduce it?

1.

2.

3.

### Environment (with versions)?

Grafana: 9.5.6

OS: centos 7 

Browser: Chrome Version 120.0.6099.234 (Official Build) (arm64)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

prometheus 2.28.1

**Comment by tonypowa** [comment] 2024-02-21 11:53
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81180

**Comment by moxious** [comment] 2024-02-21 11:54
**Summary**: The issue describes an infinite loading problem in Grafana dashboards after an upgrade, where dashboard panels fail to stop fetching data, resulting in excessive data consumption from data sources. This behavior differs from the expected outcome, where the fetching process should cease once the graph populates, and was not present in the previous Grafana version 7.5.13.

**Comment by moxious** [comment] 2024-02-21 11:55
Hello @tonypowa! Thanks for reporting this issue. It appears you are experiencing an issue with infinite loading of dashboard data after upgrading Grafana. This issue seems related to the dashboard functionality and could be best addressed by the **Dashboards Sharing squad** team. I'll tag this for their attention.

Meanwhile, for further troubleshooting, could you please provide the steps to reproduce the issue since they seem to be missing from your report (`1. 2. 3.` placeholders are there but not filled out)? This will greatly help in isolating the problem.

```json
"labels": ["team/dashboards-sharing"]
```

**Comment by moxious** [comment] 2024-02-21 11:55
**Elaboration**:


Hello @tonypowa, thank you for reaching out and providing the details of the issue you're experiencing with Grafana dashboard loading. We would like to get this addressed promptly, but we need a bit more information to fully understand the problem and to reproduce it effectively. Could you please provide the following additional information and clarifications?

1. **Reproduction Steps**: I noticed the reproduction steps are currently left empty. Detailed steps to reproduce the issue would be incredibly helpful, starting from the point of logging into Grafana, navigating to the dashboard, and observing the infinite loading.

2. **Query Details**: It sounds like there might be an issue with the query configurations that is causing excessive data fetching. Could you share the specific query or queries that are running when you experience the infinite loading? If possible, provide the query text or any settings that might be related to this problem.

3. **Browser Developer Console**: Are there any errors or warnings in the browser’s developer console when the issue occurs? These can often provide crucial insight into what might be going wrong.

4. **Grafana Server Logs**: Checking the server logs for errors during the time when the infinite fetching occurs might point us to the source of the issue. Would you be able to share any relevant logs from around that time?

5. **Screenshot Accessibility**: The images you've linked seem to be inaccessible (possibly due to a broken URL). Could you please re-upload the screenshots directly to the GitHub issue, ensuring their visibility, so we can see exactly what you're experiencing?

6. **Comparison**: Is there anything notably different in the dashboard settings or the panel setup between the Grafana instance that is working correctly and the one that exhibits the issue?

7. **Network Activity**: During the infinite loading, how does the network activity look in the browser’s developer tools? If there are multiple queries being executed repeatedly, this might indicate an issue with the dashboard’s refresh settings or a potential bug.

Once we have this information, we will be in a much better position to assist you in resolving this issue. Thank you for your cooperation and contribution to the Grafana community!

**Closed** 2024-09-27 10:42 UTC
