### ISSUE TITLE
Provisioning: Azure SQLMI Datasource can't be configured to use Azure Authentication

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#166] opened 2023-12-20 07:43 UTC
### What happened?

I'm trying to provision a connection to an Azure SQL Managed Instance as a Grafana datasource from a YAML file to avoid having it tweakable in the UI by users. I have confirmed that the provided URL, tenant, client, and secret work correctly from the datasource management page in the Grafana UI when logged in as admin. Using the same tenant/client/secret/URI in the jsonData field of a datasource.yml file does not work. The syntax for doing this in a provisioning file is undocumented so I've been looking at the Go source code in grafana/pkg/tsdb/mssql/mssql.go and trying to guess at correct variable names/capitalization, since the variable names in Go source do not correspond exactly to expected JSON values.

### What did you expect to happen?

I expected to provision a SQLMI data source.

### Did this work before?

no

### How do we reproduce it?

```

$ cat <<EOF > /etc/grafana/provisioning/datasources/datasource.yaml

apiVersion: 1

datasources:

 - name: SQLMI

 type: mssql

 url: censored.whoops.nope.database.windows.net:1433

 jsonData:

 database: Foo

 authenticationType: "AzureAuthentication"

 azureAuthType: "clientsecret"

 tenantId: "asd;flkasjdf;laksfja;sdl"

 clientId: "asdfa;lsdfj;asdlkja;sdfkja;sfkl"

 encrypt: 'true'

 secureJsonData:

 clientSecret: "ads;fkj;sdlkfj;asldfja;sdfklj"

EOF

```

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.2

OS: Win10

Browser: MS Edge

### Grafana platform?

Kubernetes

### Datasource(s)?

MSSQL

**Comment by tonypowa** [comment] 2023-12-20 07:43
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78711

**Comment by moxious** [comment] 2023-12-20 07:43
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment] 2023-12-20 07:44
**Triage summary**: The issue is about being unable to provision an Azure SQL Managed Instance as a Grafana datasource using YAML file with Azure Authentication. The user has successfully configured authentication via the UI but encounters issues when transferring the same settings to a provisioning YAML file, indicating a potential lack of documentation and/or support for this method.

**Recommended labels**:

area/provisioning
datasource/MSSQL
type/feature-request
type/docs

**Comment by moxious** [comment] 2023-12-20 07:44
Hello @tonypowa, this issue seems related to configuring an external datasource within Grafana, which suggests that it likely belongs to the **AWS Datasources project**. However, it is precise to Azure SQL Managed Instance and there might be a more specific team/project dedicated to Azure or similar cloud services. Could you provide additional details to pinpoint the setup issue, like error messages or logs? This information will help identify the exact problem and improve the datasource documentation or the provisioning process.

**Comment by moxious** [comment] 2023-12-20 07:44
**Elaboration**:


Hello @tonypowa, thank you for reaching out to us with your issue regarding the provisioning of an Azure SQL Managed Instance datasource in Grafana from a YAML file.

Before we can effectively assist you, we will need a bit more information regarding the issue you've encountered. Kindly answer the following questions and provide any additional details that you think might be relevant:

1. When you say the provisioning "does not work" with the YAML file, could you provide more specific details? For example, are there any error messages that occur when Grafana tries to parse or use the YAML file you've created?

2. Have you been able to successfully provision other types of datasources with a similar YAML configuration, or is this issue specific to Azure SQLMI with Azure Authentication?

3. Could you include any errors from Grafana logs that relate to this provisioning issue? They could help identify where the provisioning process is failing.

4. Is there any difference in network configuration or access rights between the instance where you're running the UI and where you're attempting to provision through YAML?

5. It would be helpful to confirm whether you have followed the official Grafana provisioning documentation as a reference, and if you've noticed any discrepancies between the documentation and your use case. If so, can you elaborate?

6. Please make sure any sensitive information such as URLs, tenant IDs, and client secrets are masked when sharing configuration or log files.

Once we have a clear understanding of these details, we will be better equipped to troubleshoot the problem with you. Thank you for your cooperation!

**Closed** 2024-09-27 10:43 UTC
Labels: area/provisioning, datasource/MSSQL, type/docs, type/feature-request
